//! (Mostly) Literal translation of [input-event-codes.h](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h).

/// Device properties and quirks
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum InputProp {
  /// needs a pointer
  InputPropPointer,
  /// direct input devices
  InputPropDirect,
  /// has button(s) under pad
  InputPropButtonpad,
  /// touch rectangle only
  InputPropSemiMt,
  /// softbuttons at top of pad
  InputPropTopbuttonpad,
  /// is a pointing stick
  InputPropPointingStick,
  /// has accelerometer
  InputPropAccelerometer,
  /// pressure triggers clicks
  InputPropPressurepad,

  InputPropMax,
  InputPropCnt,
}

impl InputProp {
  /// The raw numeric event code, as defined by the Linux kernel.
  pub fn code(&self) -> u32 {
    match self {
      InputProp::InputPropPointer => 0x00,
      InputProp::InputPropDirect => 0x01,
      InputProp::InputPropButtonpad => 0x02,
      InputProp::InputPropSemiMt => 0x03,
      InputProp::InputPropTopbuttonpad => 0x04,
      InputProp::InputPropPointingStick => 0x05,
      InputProp::InputPropAccelerometer => 0x06,
      InputProp::InputPropPressurepad => 0x07,
      InputProp::InputPropMax => 0x1f,
      InputProp::InputPropCnt => InputProp::InputPropMax.code() + 1,
    }
  }

  /// The literal name of the constant as it appears in the Linux kernel header.
  pub fn name(&self) -> &'static str {
    match self {
      InputProp::InputPropPointer => "INPUT_PROP_POINTER",
      InputProp::InputPropDirect => "INPUT_PROP_DIRECT",
      InputProp::InputPropButtonpad => "INPUT_PROP_BUTTONPAD",
      InputProp::InputPropSemiMt => "INPUT_PROP_SEMI_MT",
      InputProp::InputPropTopbuttonpad => "INPUT_PROP_TOPBUTTONPAD",
      InputProp::InputPropPointingStick => "INPUT_PROP_POINTING_STICK",
      InputProp::InputPropAccelerometer => "INPUT_PROP_ACCELEROMETER",
      InputProp::InputPropPressurepad => "INPUT_PROP_PRESSUREPAD",
      InputProp::InputPropMax => "INPUT_PROP_MAX",
      InputProp::InputPropCnt => "INPUT_PROP_CNT",
    }
  }
}

/// Event types
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum EventTypes {
  EvSyn,
  EvKey,
  EvRel,
  EvAbs,
  EvMsc,
  EvSw,
  EvLed,
  EvSnd,
  EvRep,
  EvFf,
  EvPwr,
  EvFfStatus,
  EvMax,
  EvCnt,
}

impl EventTypes {
  /// The raw numeric event code, as defined by the Linux kernel.
  pub fn code(&self) -> u32 {
    match self {
      EventTypes::EvSyn => 0x00,
      EventTypes::EvKey => 0x01,
      EventTypes::EvRel => 0x02,
      EventTypes::EvAbs => 0x03,
      EventTypes::EvMsc => 0x04,
      EventTypes::EvSw => 0x05,
      EventTypes::EvLed => 0x11,
      EventTypes::EvSnd => 0x12,
      EventTypes::EvRep => 0x14,
      EventTypes::EvFf => 0x15,
      EventTypes::EvPwr => 0x16,
      EventTypes::EvFfStatus => 0x17,
      EventTypes::EvMax => 0x1f,
      EventTypes::EvCnt => EventTypes::EvMax.code() + 1,
    }
  }

  /// The literal name of the constant as it appears in the Linux kernel header.
  pub fn name(&self) -> &'static str {
    match self {
      EventTypes::EvSyn => "EV_SYN",
      EventTypes::EvKey => "EV_KEY",
      EventTypes::EvRel => "EV_REL",
      EventTypes::EvAbs => "EV_ABS",
      EventTypes::EvMsc => "EV_MSC",
      EventTypes::EvSw => "EV_SW",
      EventTypes::EvLed => "EV_LED",
      EventTypes::EvSnd => "EV_SND",
      EventTypes::EvRep => "EV_REP",
      EventTypes::EvFf => "EV_FF",
      EventTypes::EvPwr => "EV_PWR",
      EventTypes::EvFfStatus => "EV_FF_STATUS",
      EventTypes::EvMax => "EV_MAX",
      EventTypes::EvCnt => "EV_CNT",
    }
  }
}

/// Synchronization events.
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum Syn {
  SynReport,
  SynConfig,
  SynMtReport,
  SynDropped,
  SynMax,
  SynCnt,
}

impl Syn {
  /// The raw numeric event code, as defined by the Linux kernel.
  pub fn code(&self) -> u32 {
    match self {
      Syn::SynReport => 0,
      Syn::SynConfig => 1,
      Syn::SynMtReport => 2,
      Syn::SynDropped => 3,
      Syn::SynMax => 0xf,
      Syn::SynCnt => Syn::SynMax.code() + 1,
    }
  }

  /// The literal name of the constant as it appears in the Linux kernel header.
  pub fn name(&self) -> &'static str {
    match self {
      Syn::SynReport => "SYN_REPORT",
      Syn::SynConfig => "SYN_CONFIG",
      Syn::SynMtReport => "SYN_MT_REPORT",
      Syn::SynDropped => "SYN_DROPPED",
      Syn::SynMax => "SYN_MAX",
      Syn::SynCnt => "SYN_CNT",
    }
  }
}

/// Keys and buttons
///
/// Most of the keys/buttons are modeled after USB HUT 1.12
/// (see http://www.usb.org/developers/hidpage).
/// Abbreviations in the comments:
/// AC - Application Control
/// AL - Application Launch Button
/// SC - System Control
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum Key {
  KeyReserved,
  KeyEsc,
  Key1,
  Key2,
  Key3,
  Key4,
  Key5,
  Key6,
  Key7,
  Key8,
  Key9,
  Key0,
  KeyMinus,
  KeyEqual,
  KeyBackspace,
  KeyTab,
  KeyQ,
  KeyW,
  KeyE,
  KeyR,
  KeyT,
  KeyY,
  KeyU,
  KeyI,
  KeyO,
  KeyP,
  KeyLeftbrace,
  KeyRightbrace,
  KeyEnter,
  KeyLeftctrl,
  KeyA,
  KeyS,
  KeyD,
  KeyF,
  KeyG,
  KeyH,
  KeyJ,
  KeyK,
  KeyL,
  KeySemicolon,
  KeyApostrophe,
  KeyGrave,
  KeyLeftshift,
  KeyBackslash,
  KeyZ,
  KeyX,
  KeyC,
  KeyV,
  KeyB,
  KeyN,
  KeyM,
  KeyComma,
  KeyDot,
  KeySlash,
  KeyRightshift,
  KeyKpasterisk,
  KeyLeftalt,
  KeySpace,
  KeyCapslock,
  KeyF1,
  KeyF2,
  KeyF3,
  KeyF4,
  KeyF5,
  KeyF6,
  KeyF7,
  KeyF8,
  KeyF9,
  KeyF10,
  KeyNumlock,
  KeyScrolllock,
  KeyKp7,
  KeyKp8,
  KeyKp9,
  KeyKpminus,
  KeyKp4,
  KeyKp5,
  KeyKp6,
  KeyKpplus,
  KeyKp1,
  KeyKp2,
  KeyKp3,
  KeyKp0,
  KeyKpdot,

  KeyZenkakuhankaku,
  Key102nd,
  KeyF11,
  KeyF12,
  KeyRo,
  KeyKatakana,
  KeyHiragana,
  KeyHenkan,
  KeyKatakanahiragana,
  KeyMuhenkan,
  KeyKpjpcomma,
  KeyKpenter,
  KeyRightctrl,
  KeyKpslash,
  KeySysrq,
  KeyRightalt,
  KeyLinefeed,
  KeyHome,
  KeyUp,
  KeyPageup,
  KeyLeft,
  KeyRight,
  KeyEnd,
  KeyDown,
  KeyPagedown,
  KeyInsert,
  KeyDelete,
  KeyMacro,
  KeyMute,
  KeyVolumedown,
  KeyVolumeup,
  /// SC System Power Down
  KeyPower,
  KeyKpequal,
  KeyKpplusminus,
  KeyPause,
  /// AL Compiz Scale (Expose)
  KeyScale,

  KeyKpcomma,
  KeyHangeul,
  KeyHanguel,
  KeyHanja,
  KeyYen,
  KeyLeftmeta,
  KeyRightmeta,
  KeyCompose,

  /// AC Stop
  KeyStop,
  KeyAgain,
  /// AC Properties
  KeyProps,
  /// AC Undo
  KeyUndo,
  KeyFront,
  /// AC Copy
  KeyCopy,
  /// AC Open
  KeyOpen,
  /// AC Paste
  KeyPaste,
  /// AC Search
  KeyFind,
  /// AC Cut
  KeyCut,
  /// AL Integrated Help Center
  KeyHelp,
  /// Menu (show menu)
  KeyMenu,
  /// AL Calculator
  KeyCalc,
  KeySetup,
  /// SC System Sleep
  KeySleep,
  /// System Wake Up
  KeyWakeup,
  /// AL Local Machine Browser
  KeyFile,
  KeySendfile,
  KeyDeletefile,
  KeyXfer,
  KeyProg1,
  KeyProg2,
  /// AL Internet Browser
  KeyWww,
  KeyMsdos,
  /// AL Terminal Lock/Screensaver
  KeyCoffee,
  KeyScreenlock,
  /// Display orientation for e.g. tablets
  KeyRotateDisplay,
  KeyDirection,
  KeyCyclewindows,
  KeyMail,
  /// AC Bookmarks
  KeyBookmarks,
  KeyComputer,
  /// AC Back
  KeyBack,
  /// AC Forward
  KeyForward,
  KeyClosecd,
  KeyEjectcd,
  KeyEjectclosecd,
  KeyNextsong,
  KeyPlaypause,
  KeyPrevioussong,
  KeyStopcd,
  KeyRecord,
  KeyRewind,
  /// Media Select Telephone
  KeyPhone,
  KeyIso,
  /// AL Consumer Control Configuration
  KeyConfig,
  /// AC Home
  KeyHomepage,
  /// AC Refresh
  KeyRefresh,
  /// AC Exit
  KeyExit,
  KeyMove,
  KeyEdit,
  KeyScrollup,
  KeyScrolldown,
  KeyKpleftparen,
  KeyKprightparen,
  /// AC New
  KeyNew,
  /// AC Redo/Repeat
  KeyRedo,

  KeyF13,
  KeyF14,
  KeyF15,
  KeyF16,
  KeyF17,
  KeyF18,
  KeyF19,
  KeyF20,
  KeyF21,
  KeyF22,
  KeyF23,
  KeyF24,

  KeyPlaycd,
  KeyPausecd,
  KeyProg3,
  KeyProg4,
  /// AC Desktop Show All Applications
  KeyAllApplications,
  KeyDashboard,
  KeySuspend,
  /// AC Close
  KeyClose,
  KeyPlay,
  KeyFastforward,
  KeyBassboost,
  /// AC Print
  KeyPrint,
  KeyHp,
  KeyCamera,
  KeySound,
  KeyQuestion,
  KeyEmail,
  KeyChat,
  KeySearch,
  KeyConnect,
  /// AL Checkbook/Finance
  KeyFinance,
  KeySport,
  KeyShop,
  KeyAlterase,
  /// AC Cancel
  KeyCancel,
  KeyBrightnessdown,
  KeyBrightnessup,
  KeyMedia,

  /// Cycle between available video outputs (Monitor/LCD/TV-out/etc)
  KeySwitchvideomode,
  KeyKbdillumtoggle,
  KeyKbdillumdown,
  KeyKbdillumup,

  /// AC Send
  KeySend,
  /// AC Reply
  KeyReply,
  /// AC Forward Msg
  KeyForwardmail,
  /// AC Save
  KeySave,
  KeyDocuments,

  KeyBattery,

  KeyBluetooth,
  KeyWlan,
  KeyUwb,

  KeyUnknown,

  /// drive next video source
  KeyVideoNext,
  /// drive previous video source
  KeyVideoPrev,
  /// brightness up, after max is min
  KeyBrightnessCycle,
  /// Set Auto Brightness: manual brightness control is off, rely on ambient
  KeyBrightnessAuto,
  KeyBrightnessZero,
  /// display device to off state
  KeyDisplayOff,

  /// Wireless WAN (LTE, UMTS, GSM, etc.)
  KeyWwan,
  KeyWimax,
  /// Key that controls all radios
  KeyRfkill,

  /// Mute / unmute the microphone
  KeyMicmute,

  // Code 255 is reserved for special needs of AT keyboard driver
  BtnMisc,
  Btn0,
  Btn1,
  Btn2,
  Btn3,
  Btn4,
  Btn5,
  Btn6,
  Btn7,
  Btn8,
  Btn9,

  BtnMouse,
  BtnLeft,
  BtnRight,
  BtnMiddle,
  BtnSide,
  BtnExtra,
  BtnForward,
  BtnBack,
  BtnTask,

  BtnJoystick,
  BtnTrigger,
  BtnThumb,
  BtnThumb2,
  BtnTop,
  BtnTop2,
  BtnPinkie,
  BtnBase,
  BtnBase2,
  BtnBase3,
  BtnBase4,
  BtnBase5,
  BtnBase6,
  BtnDead,

  BtnGamepad,
  BtnSouth,
  BtnA,
  BtnEast,
  BtnB,
  BtnC,
  BtnNorth,
  BtnX,
  BtnWest,
  BtnY,
  BtnZ,
  BtnTl,
  BtnTr,
  BtnTl2,
  BtnTr2,
  BtnSelect,
  BtnStart,
  BtnMode,
  BtnThumbl,
  BtnThumbr,

  BtnDigi,
  BtnToolPen,
  BtnToolRubber,
  BtnToolBrush,
  BtnToolPencil,
  BtnToolAirbrush,
  BtnToolFinger,
  BtnToolMouse,
  BtnToolLens,
  /// Five fingers on trackpad
  BtnToolQuinttap,
  BtnStylus3,
  BtnTouch,
  BtnStylus,
  BtnStylus2,
  BtnToolDoubletap,
  BtnToolTripletap,
  /// Four fingers on trackpad
  BtnToolQuadtap,

  BtnWheel,
  BtnGearDown,
  BtnGearUp,

  KeyOk,
  KeySelect,
  KeyGoto,
  KeyClear,
  KeyPower2,
  KeyOption,
  /// AL OEM Features/Tips/Tutorial
  KeyInfo,
  KeyTime,
  KeyVendor,
  KeyArchive,
  /// Media Select Program Guide
  KeyProgram,
  KeyChannel,
  KeyFavorites,
  KeyEpg,
  /// Media Select Home
  KeyPvr,
  KeyMhp,
  KeyLanguage,
  KeyTitle,
  KeySubtitle,
  KeyAngle,
  /// AC View Toggle
  KeyFullScreen,
  KeyZoom,
  KeyMode,
  KeyKeyboard,
  /// HUTRR37: Aspect
  KeyAspectRatio,
  KeyScreen,
  /// Media Select Computer
  KeyPc,
  /// Media Select TV
  KeyTv,
  /// Media Select Cable
  KeyTv2,
  /// Media Select VCR
  KeyVcr,
  /// VCR Plus
  KeyVcr2,
  /// Media Select Satellite
  KeySat,
  KeySat2,
  /// Media Select CD
  KeyCd,
  /// Media Select Tape
  KeyTape,
  KeyRadio,
  /// Media Select Tuner
  KeyTuner,
  KeyPlayer,
  KeyText,
  /// Media Select DVD
  KeyDvd,
  KeyAux,
  KeyMp3,
  /// AL Audio Browser
  KeyAudio,
  /// AL Movie Browser
  KeyVideo,
  KeyDirectory,
  KeyList,
  /// Media Select Messages
  KeyMemo,
  KeyCalendar,
  KeyRed,
  KeyGreen,
  KeyYellow,
  KeyBlue,
  /// Channel Increment
  KeyChannelup,
  /// Channel Decrement
  KeyChanneldown,
  KeyFirst,
  /// Recall Last
  KeyLast,
  KeyAb,
  KeyNext,
  KeyRestart,
  KeySlow,
  KeyShuffle,
  KeyBreak,
  KeyPrevious,
  KeyDigits,
  KeyTeen,
  KeyTwen,
  /// Media Select Video Phone
  KeyVideophone,
  /// Media Select Games
  KeyGames,
  /// AC Zoom In
  KeyZoomin,
  /// AC Zoom Out
  KeyZoomout,
  /// AC Zoom
  KeyZoomreset,
  /// AL Word Processor
  KeyWordprocessor,
  /// AL Text Editor
  KeyEditor,
  /// AL Spreadsheet
  KeySpreadsheet,
  /// AL Graphics Editor
  KeyGraphicseditor,
  /// AL Presentation App
  KeyPresentation,
  /// AL Database App
  KeyDatabase,
  /// AL Newsreader
  KeyNews,
  /// AL Voicemail
  KeyVoicemail,
  /// AL Contacts/Address Book
  KeyAddressbook,
  /// AL Instant Messaging
  KeyMessenger,
  /// Turn display (LCD) on and off
  KeyDisplaytoggle,
  KeyBrightnessToggle,
  /// AL Spell Check
  KeySpellcheck,
  /// AL Logoff
  KeyLogoff,

  KeyDollar,
  KeyEuro,

  /// Consumer - transport controls
  KeyFrameback,
  KeyFrameforward,
  /// GenDesc - system context menu
  KeyContextMenu,
  /// Consumer - transport control
  KeyMediaRepeat,
  /// 10 channels up (10+)
  Key10channelsup,
  /// 10 channels down (10-)
  Key10channelsdown,
  /// AL Image Browser
  KeyImages,
  /// Show/hide the notification center
  KeyNotificationCenter,
  /// Answer incoming call
  KeyPickupPhone,
  /// Decline incoming call
  KeyHangupPhone,
  /// AL Phone Syncing
  KeyLinkPhone,

  KeyDelEol,
  KeyDelEos,
  KeyInsLine,
  KeyDelLine,

  KeyFn,
  KeyFnEsc,
  KeyFnF1,
  KeyFnF2,
  KeyFnF3,
  KeyFnF4,
  KeyFnF5,
  KeyFnF6,
  KeyFnF7,
  KeyFnF8,
  KeyFnF9,
  KeyFnF10,
  KeyFnF11,
  KeyFnF12,
  KeyFn1,
  KeyFn2,
  KeyFnD,
  KeyFnE,
  KeyFnF,
  KeyFnS,
  KeyFnB,
  KeyFnRightShift,

  KeyBrlDot1,
  KeyBrlDot2,
  KeyBrlDot3,
  KeyBrlDot4,
  KeyBrlDot5,
  KeyBrlDot6,
  KeyBrlDot7,
  KeyBrlDot8,
  KeyBrlDot9,
  KeyBrlDot10,

  /// used by phones, remote controls,
  KeyNumeric0,
  /// and other keypads
  KeyNumeric1,
  KeyNumeric2,
  KeyNumeric3,
  KeyNumeric4,
  KeyNumeric5,
  KeyNumeric6,
  KeyNumeric7,
  KeyNumeric8,
  KeyNumeric9,
  KeyNumericStar,
  KeyNumericPound,
  /// Phone key A - HUT Telephony 0xb9
  KeyNumericA,
  KeyNumericB,
  KeyNumericC,
  KeyNumericD,

  KeyCameraFocus,
  /// WiFi Protected Setup key
  KeyWpsButton,

  /// Request switch touchpad on or off
  KeyTouchpadToggle,
  KeyTouchpadOn,
  KeyTouchpadOff,

  KeyCameraZoomin,
  KeyCameraZoomout,
  KeyCameraUp,
  KeyCameraDown,
  KeyCameraLeft,
  KeyCameraRight,

  KeyAttendantOn,
  KeyAttendantOff,
  /// Attendant call on or off
  KeyAttendantToggle,
  /// Reading light on or off
  KeyLightsToggle,

  BtnDpadUp,
  BtnDpadDown,
  BtnDpadLeft,
  BtnDpadRight,

  BtnGripl,
  BtnGripr,
  BtnGripl2,
  BtnGripr2,

  /// Ambient light sensor
  KeyAlsToggle,
  /// Display rotation lock
  KeyRotateLockToggle,
  /// Display refresh rate toggle
  KeyRefreshRateToggle,

  /// AL Button Configuration
  KeyButtonconfig,
  /// AL Task/Project Manager
  KeyTaskmanager,
  /// AL Log/Journal/Timecard
  KeyJournal,
  /// AL Control Panel
  KeyControlpanel,
  /// AL Select Task/Application
  KeyAppselect,
  /// AL Screen Saver
  KeyScreensaver,
  /// Listening Voice Command
  KeyVoicecommand,
  /// AL Context-aware desktop assistant
  KeyAssistant,
  /// AC Next Keyboard Layout Select
  KeyKbdLayoutNext,
  /// Show/hide emoji picker (HUTRR101)
  KeyEmojiPicker,
  /// Start or Stop Voice Dictation Session (HUTRR99)
  KeyDictate,
  /// Enables programmatic access to camera devices. (HUTRR72)
  KeyCameraAccessEnable,
  /// Disables programmatic access to camera devices. (HUTRR72)
  KeyCameraAccessDisable,
  /// Toggles the current state of the camera access control. (HUTRR72)
  KeyCameraAccessToggle,
  /// Toggles the system bound accessibility UI/command (HUTRR116)
  KeyAccessibility,
  /// Toggles the system-wide "Do Not Disturb" control (HUTRR94)
  KeyDoNotDisturb,

  /// Set Brightness to Minimum
  KeyBrightnessMin,
  /// Set Brightness to Maximum
  KeyBrightnessMax,

  // Keycodes for hotkeys toggling the electronic privacy screen found on some
  // laptops on/off. Note when the embedded-controller turns on/off the eprivacy
  // screen itself then the state should be reported through drm connecter props:
  // https://www.kernel.org/doc/html/latest/gpu/drm-kms.html#standard-connector-properties
  // Except when implementing the drm connecter properties API is not possible
  // because e.g. the firmware does not allow querying the presence and/or status
  // of the eprivacy screen at boot.
  KeyEprivacyScreenOn,
  KeyEprivacyScreenOff,

  /// AL Action on Selection (HUTRR119)
  KeyActionOnSelection,
  /// AL Contextual Insertion (HUTRR119)
  KeyContextualInsert,
  /// AL Contextual Query (HUTRR119)
  KeyContextualQuery,

  KeyKbdinputassistPrev,
  KeyKbdinputassistNext,
  KeyKbdinputassistPrevgroup,
  KeyKbdinputassistNextgroup,
  KeyKbdinputassistAccept,
  KeyKbdinputassistCancel,

  // Diagonal movement keys
  KeyRightUp,
  KeyRightDown,
  KeyLeftUp,
  KeyLeftDown,

  /// Show Device's Root Menu
  KeyRootMenu,
  // Show Top Menu of the Media (e.g. DVD)
  KeyMediaTopMenu,
  KeyNumeric11,
  KeyNumeric12,
  // Toggle Audio Description: refers to an audio service that helps blind and
  // visually impaired consumers understand the action in a program. Note: in
  // some countries this is referred to as "Video Description".
  KeyAudioDesc,
  Key3dMode,
  KeyNextFavorite,
  KeyStopRecord,
  KeyPauseRecord,
  /// Video on Demand
  KeyVod,
  KeyUnmute,
  KeyFastreverse,
  KeySlowreverse,
  // Control a data application associated with the currently viewed channel,
  // e.g. teletext or data broadcast application (MHEG, MHP, HbbTV, etc.)
  KeyData,
  KeyOnscreenKeyboard,
  // Electronic privacy screen control
  KeyPrivacyScreenToggle,

  // Select an area of screen to be copied
  KeySelectiveScreenshot,

  // Move the focus to the next or previous user controllable element within a UI container
  KeyNextElement,
  KeyPreviousElement,

  // Toggle Autopilot engagement
  KeyAutopilotEngageToggle,

  // Shortcut Keys
  KeyMarkWaypoint,
  KeySos,
  KeyNavChart,
  KeyFishingChart,
  KeySingleRangeRadar,
  KeyDualRangeRadar,
  KeyRadarOverlay,
  KeyTraditionalSonar,
  KeyClearvuSonar,
  KeySidevuSonar,
  KeyNavInfo,
  KeyBrightnessMenu,

  // Some keyboards have keys which do not have a defined meaning, these keys
  // are intended to be programmed / bound to macros by the user. For most
  // keyboards with these macro-keys the key-sequence to inject, or action to
  // take, is all handled by software on the host side. So from the kernel's
  // point of view these are just normal keys.

  // The KEY_MACRO# codes below are intended for such keys, which may be labeled
  // e.g. G1-G18, or S1 - S30. The KEY_MACRO# codes MUST NOT be used for keys
  // where the marking on the key does indicate a defined meaning / purpose.

  // The KEY_MACRO# codes MUST also NOT be used as fallback for when no existing
  // KEY_FOO define matches the marking / purpose. In this case a new KEY_FOO
  // define MUST be added.
  KeyMacro1,
  KeyMacro2,
  KeyMacro3,
  KeyMacro4,
  KeyMacro5,
  KeyMacro6,
  KeyMacro7,
  KeyMacro8,
  KeyMacro9,
  KeyMacro10,
  KeyMacro11,
  KeyMacro12,
  KeyMacro13,
  KeyMacro14,
  KeyMacro15,
  KeyMacro16,
  KeyMacro17,
  KeyMacro18,
  KeyMacro19,
  KeyMacro20,
  KeyMacro21,
  KeyMacro22,
  KeyMacro23,
  KeyMacro24,
  KeyMacro25,
  KeyMacro26,
  KeyMacro27,
  KeyMacro28,
  KeyMacro29,
  KeyMacro30,

  // Some keyboards with the macro-keys described above have some extra keys
  // for controlling the host-side software responsible for the macro handling:
  // -A macro recording start/stop key. Note that not all keyboards which emit
  //  KEY_MACRO_RECORD_START will also emit KEY_MACRO_RECORD_STOP if
  //  KEY_MACRO_RECORD_STOP is not advertised, then KEY_MACRO_RECORD_START
  //  should be interpreted as a recording start/stop toggle;
  // -Keys for switching between different macro (pre)sets, either a key for
  //  cycling through the configured presets or keys to directly select a preset.
  KeyMacroRecordStart,
  KeyMacroRecordStop,
  KeyMacroPresetCycle,
  KeyMacroPreset1,
  KeyMacroPreset2,
  KeyMacroPreset3,

  // Some keyboards have a buildin LCD panel where the contents are controlled
  // by the host. Often these have a number of keys directly below the LCD
  // intended for controlling a menu shown on the LCD. These keys often don't
  // have any labeling so we just name them KEY_KBD_LCD_MENU#
  KeyKbdLcdMenu1,
  KeyKbdLcdMenu2,
  KeyKbdLcdMenu3,
  KeyKbdLcdMenu4,
  KeyKbdLcdMenu5,

  // Performance Boost key (Alienware)/G-Mode key (Dell)
  KeyPerformance,

  BtnTriggerHappy,
  BtnTriggerHappy1,
  BtnTriggerHappy2,
  BtnTriggerHappy3,
  BtnTriggerHappy4,
  BtnTriggerHappy5,
  BtnTriggerHappy6,
  BtnTriggerHappy7,
  BtnTriggerHappy8,
  BtnTriggerHappy9,
  BtnTriggerHappy10,
  BtnTriggerHappy11,
  BtnTriggerHappy12,
  BtnTriggerHappy13,
  BtnTriggerHappy14,
  BtnTriggerHappy15,
  BtnTriggerHappy16,
  BtnTriggerHappy17,
  BtnTriggerHappy18,
  BtnTriggerHappy19,
  BtnTriggerHappy20,
  BtnTriggerHappy21,
  BtnTriggerHappy22,
  BtnTriggerHappy23,
  BtnTriggerHappy24,
  BtnTriggerHappy25,
  BtnTriggerHappy26,
  BtnTriggerHappy27,
  BtnTriggerHappy28,
  BtnTriggerHappy29,
  BtnTriggerHappy30,
  BtnTriggerHappy31,
  BtnTriggerHappy32,
  BtnTriggerHappy33,
  BtnTriggerHappy34,
  BtnTriggerHappy35,
  BtnTriggerHappy36,
  BtnTriggerHappy37,
  BtnTriggerHappy38,
  BtnTriggerHappy39,
  BtnTriggerHappy40,

  // We avoid low common keys in module aliases so they don't get huge.
  KeyMinInteresting,
  KeyMax,
  KeyCnt,
}

impl Key {
  /// The raw numeric event code, as defined by the Linux kernel.
  pub fn code(&self) -> u32 {
    match self {
      Key::KeyReserved => 0,
      Key::KeyEsc => 1,
      Key::Key1 => 2,
      Key::Key2 => 3,
      Key::Key3 => 4,
      Key::Key4 => 5,
      Key::Key5 => 6,
      Key::Key6 => 7,
      Key::Key7 => 8,
      Key::Key8 => 9,
      Key::Key9 => 10,
      Key::Key0 => 11,
      Key::KeyMinus => 12,
      Key::KeyEqual => 13,
      Key::KeyBackspace => 14,
      Key::KeyTab => 15,
      Key::KeyQ => 16,
      Key::KeyW => 17,
      Key::KeyE => 18,
      Key::KeyR => 19,
      Key::KeyT => 20,
      Key::KeyY => 21,
      Key::KeyU => 22,
      Key::KeyI => 23,
      Key::KeyO => 24,
      Key::KeyP => 25,
      Key::KeyLeftbrace => 26,
      Key::KeyRightbrace => 27,
      Key::KeyEnter => 28,
      Key::KeyLeftctrl => 29,
      Key::KeyA => 30,
      Key::KeyS => 31,
      Key::KeyD => 32,
      Key::KeyF => 33,
      Key::KeyG => 34,
      Key::KeyH => 35,
      Key::KeyJ => 36,
      Key::KeyK => 37,
      Key::KeyL => 38,
      Key::KeySemicolon => 39,
      Key::KeyApostrophe => 40,
      Key::KeyGrave => 41,
      Key::KeyLeftshift => 42,
      Key::KeyBackslash => 43,
      Key::KeyZ => 44,
      Key::KeyX => 45,
      Key::KeyC => 46,
      Key::KeyV => 47,
      Key::KeyB => 48,
      Key::KeyN => 49,
      Key::KeyM => 50,
      Key::KeyComma => 51,
      Key::KeyDot => 52,
      Key::KeySlash => 53,
      Key::KeyRightshift => 54,
      Key::KeyKpasterisk => 55,
      Key::KeyLeftalt => 56,
      Key::KeySpace => 57,
      Key::KeyCapslock => 58,
      Key::KeyF1 => 59,
      Key::KeyF2 => 60,
      Key::KeyF3 => 61,
      Key::KeyF4 => 62,
      Key::KeyF5 => 63,
      Key::KeyF6 => 64,
      Key::KeyF7 => 65,
      Key::KeyF8 => 66,
      Key::KeyF9 => 67,
      Key::KeyF10 => 68,
      Key::KeyNumlock => 69,
      Key::KeyScrolllock => 70,
      Key::KeyKp7 => 71,
      Key::KeyKp8 => 72,
      Key::KeyKp9 => 73,
      Key::KeyKpminus => 74,
      Key::KeyKp4 => 75,
      Key::KeyKp5 => 76,
      Key::KeyKp6 => 77,
      Key::KeyKpplus => 78,
      Key::KeyKp1 => 79,
      Key::KeyKp2 => 80,
      Key::KeyKp3 => 81,
      Key::KeyKp0 => 82,
      Key::KeyKpdot => 83,
      Key::KeyZenkakuhankaku => 85,
      Key::Key102nd => 86,
      Key::KeyF11 => 87,
      Key::KeyF12 => 88,
      Key::KeyRo => 89,
      Key::KeyKatakana => 90,
      Key::KeyHiragana => 91,
      Key::KeyHenkan => 92,
      Key::KeyKatakanahiragana => 93,
      Key::KeyMuhenkan => 94,
      Key::KeyKpjpcomma => 95,
      Key::KeyKpenter => 96,
      Key::KeyRightctrl => 97,
      Key::KeyKpslash => 98,
      Key::KeySysrq => 99,
      Key::KeyRightalt => 100,
      Key::KeyLinefeed => 101,
      Key::KeyHome => 102,
      Key::KeyUp => 103,
      Key::KeyPageup => 104,
      Key::KeyLeft => 105,
      Key::KeyRight => 106,
      Key::KeyEnd => 107,
      Key::KeyDown => 108,
      Key::KeyPagedown => 109,
      Key::KeyInsert => 110,
      Key::KeyDelete => 111,
      Key::KeyMacro => 112,
      Key::KeyMute => 113,
      Key::KeyVolumedown => 114,
      Key::KeyVolumeup => 115,
      Key::KeyPower => 116,
      Key::KeyKpequal => 117,
      Key::KeyKpplusminus => 118,
      Key::KeyPause => 119,
      Key::KeyScale => 120,
      Key::KeyKpcomma => 121,
      Key::KeyHangeul => 122,
      Key::KeyHanguel => Key::KeyHangeul.code(),
      Key::KeyHanja => 123,
      Key::KeyYen => 124,
      Key::KeyLeftmeta => 125,
      Key::KeyRightmeta => 126,
      Key::KeyCompose => 127,
      Key::KeyStop => 128,
      Key::KeyAgain => 129,
      Key::KeyProps => 130,
      Key::KeyUndo => 131,
      Key::KeyFront => 132,
      Key::KeyCopy => 133,
      Key::KeyOpen => 134,
      Key::KeyPaste => 135,
      Key::KeyFind => 136,
      Key::KeyCut => 137,
      Key::KeyHelp => 138,
      Key::KeyMenu => 139,
      Key::KeyCalc => 140,
      Key::KeySetup => 141,
      Key::KeySleep => 142,
      Key::KeyWakeup => 143,
      Key::KeyFile => 144,
      Key::KeySendfile => 145,
      Key::KeyDeletefile => 146,
      Key::KeyXfer => 147,
      Key::KeyProg1 => 148,
      Key::KeyProg2 => 149,
      Key::KeyWww => 150,
      Key::KeyMsdos => 151,
      Key::KeyCoffee => 152,
      Key::KeyScreenlock => Key::KeyCoffee.code(),
      Key::KeyRotateDisplay => 153,
      Key::KeyDirection => Key::KeyRotateDisplay.code(),
      Key::KeyCyclewindows => 154,
      Key::KeyMail => 155,
      Key::KeyBookmarks => 156,
      Key::KeyComputer => 157,
      Key::KeyBack => 158,
      Key::KeyForward => 159,
      Key::KeyClosecd => 160,
      Key::KeyEjectcd => 161,
      Key::KeyEjectclosecd => 162,
      Key::KeyNextsong => 163,
      Key::KeyPlaypause => 164,
      Key::KeyPrevioussong => 165,
      Key::KeyStopcd => 166,
      Key::KeyRecord => 167,
      Key::KeyRewind => 168,
      Key::KeyPhone => 169,
      Key::KeyIso => 170,
      Key::KeyConfig => 171,
      Key::KeyHomepage => 172,
      Key::KeyRefresh => 173,
      Key::KeyExit => 174,
      Key::KeyMove => 175,
      Key::KeyEdit => 176,
      Key::KeyScrollup => 177,
      Key::KeyScrolldown => 178,
      Key::KeyKpleftparen => 179,
      Key::KeyKprightparen => 180,
      Key::KeyNew => 181,
      Key::KeyRedo => 182,
      Key::KeyF13 => 183,
      Key::KeyF14 => 184,
      Key::KeyF15 => 185,
      Key::KeyF16 => 186,
      Key::KeyF17 => 187,
      Key::KeyF18 => 188,
      Key::KeyF19 => 189,
      Key::KeyF20 => 190,
      Key::KeyF21 => 191,
      Key::KeyF22 => 192,
      Key::KeyF23 => 193,
      Key::KeyF24 => 194,
      Key::KeyPlaycd => 200,
      Key::KeyPausecd => 201,
      Key::KeyProg3 => 202,
      Key::KeyProg4 => 203,
      Key::KeyAllApplications => 204,
      Key::KeyDashboard => Key::KeyAllApplications.code(),
      Key::KeySuspend => 205,
      Key::KeyClose => 206,
      Key::KeyPlay => 207,
      Key::KeyFastforward => 208,
      Key::KeyBassboost => 209,
      Key::KeyPrint => 210,
      Key::KeyHp => 211,
      Key::KeyCamera => 212,
      Key::KeySound => 213,
      Key::KeyQuestion => 214,
      Key::KeyEmail => 215,
      Key::KeyChat => 216,
      Key::KeySearch => 217,
      Key::KeyConnect => 218,
      Key::KeyFinance => 219,
      Key::KeySport => 220,
      Key::KeyShop => 221,
      Key::KeyAlterase => 222,
      Key::KeyCancel => 223,
      Key::KeyBrightnessdown => 224,
      Key::KeyBrightnessup => 225,
      Key::KeyMedia => 226,
      Key::KeySwitchvideomode => 227,
      Key::KeyKbdillumtoggle => 228,
      Key::KeyKbdillumdown => 229,
      Key::KeyKbdillumup => 230,
      Key::KeySend => 231,
      Key::KeyReply => 232,
      Key::KeyForwardmail => 233,
      Key::KeySave => 234,
      Key::KeyDocuments => 235,
      Key::KeyBattery => 236,
      Key::KeyBluetooth => 237,
      Key::KeyWlan => 238,
      Key::KeyUwb => 239,
      Key::KeyUnknown => 240,
      Key::KeyVideoNext => 241,
      Key::KeyVideoPrev => 242,
      Key::KeyBrightnessCycle => 243,
      Key::KeyBrightnessAuto => 244,
      Key::KeyBrightnessZero => Key::KeyBrightnessAuto.code(),
      Key::KeyDisplayOff => 245,
      Key::KeyWwan => 246,
      Key::KeyWimax => Key::KeyWwan.code(),
      Key::KeyRfkill => 247,
      Key::KeyMicmute => 248,
      Key::BtnMisc => 0x100,
      Key::Btn0 => 0x100,
      Key::Btn1 => 0x101,
      Key::Btn2 => 0x102,
      Key::Btn3 => 0x103,
      Key::Btn4 => 0x104,
      Key::Btn5 => 0x105,
      Key::Btn6 => 0x106,
      Key::Btn7 => 0x107,
      Key::Btn8 => 0x108,
      Key::Btn9 => 0x109,
      Key::BtnMouse => 0x110,
      Key::BtnLeft => 0x110,
      Key::BtnRight => 0x111,
      Key::BtnMiddle => 0x112,
      Key::BtnSide => 0x113,
      Key::BtnExtra => 0x114,
      Key::BtnForward => 0x115,
      Key::BtnBack => 0x116,
      Key::BtnTask => 0x117,
      Key::BtnJoystick => 0x120,
      Key::BtnTrigger => 0x120,
      Key::BtnThumb => 0x121,
      Key::BtnThumb2 => 0x122,
      Key::BtnTop => 0x123,
      Key::BtnTop2 => 0x124,
      Key::BtnPinkie => 0x125,
      Key::BtnBase => 0x126,
      Key::BtnBase2 => 0x127,
      Key::BtnBase3 => 0x128,
      Key::BtnBase4 => 0x129,
      Key::BtnBase5 => 0x12a,
      Key::BtnBase6 => 0x12b,
      Key::BtnDead => 0x12f,
      Key::BtnGamepad => 0x130,
      Key::BtnSouth => 0x130,
      Key::BtnA => Key::BtnSouth.code(),
      Key::BtnEast => 0x131,
      Key::BtnB => Key::BtnEast.code(),
      Key::BtnC => 0x132,
      Key::BtnNorth => 0x133,
      Key::BtnX => Key::BtnNorth.code(),
      Key::BtnWest => 0x134,
      Key::BtnY => Key::BtnWest.code(),
      Key::BtnZ => 0x135,
      Key::BtnTl => 0x136,
      Key::BtnTr => 0x137,
      Key::BtnTl2 => 0x138,
      Key::BtnTr2 => 0x139,
      Key::BtnSelect => 0x13a,
      Key::BtnStart => 0x13b,
      Key::BtnMode => 0x13c,
      Key::BtnThumbl => 0x13d,
      Key::BtnThumbr => 0x13e,
      Key::BtnDigi => 0x140,
      Key::BtnToolPen => 0x140,
      Key::BtnToolRubber => 0x141,
      Key::BtnToolBrush => 0x142,
      Key::BtnToolPencil => 0x143,
      Key::BtnToolAirbrush => 0x144,
      Key::BtnToolFinger => 0x145,
      Key::BtnToolMouse => 0x146,
      Key::BtnToolLens => 0x147,
      Key::BtnToolQuinttap => 0x148,
      Key::BtnStylus3 => 0x149,
      Key::BtnTouch => 0x14a,
      Key::BtnStylus => 0x14b,
      Key::BtnStylus2 => 0x14c,
      Key::BtnToolDoubletap => 0x14d,
      Key::BtnToolTripletap => 0x14e,
      Key::BtnToolQuadtap => 0x14f,
      Key::BtnWheel => 0x150,
      Key::BtnGearDown => 0x150,
      Key::BtnGearUp => 0x151,
      Key::KeyOk => 0x160,
      Key::KeySelect => 0x161,
      Key::KeyGoto => 0x162,
      Key::KeyClear => 0x163,
      Key::KeyPower2 => 0x164,
      Key::KeyOption => 0x165,
      Key::KeyInfo => 0x166,
      Key::KeyTime => 0x167,
      Key::KeyVendor => 0x168,
      Key::KeyArchive => 0x169,
      Key::KeyProgram => 0x16a,
      Key::KeyChannel => 0x16b,
      Key::KeyFavorites => 0x16c,
      Key::KeyEpg => 0x16d,
      Key::KeyPvr => 0x16e,
      Key::KeyMhp => 0x16f,
      Key::KeyLanguage => 0x170,
      Key::KeyTitle => 0x171,
      Key::KeySubtitle => 0x172,
      Key::KeyAngle => 0x173,
      Key::KeyFullScreen => 0x174,
      Key::KeyZoom => Key::KeyFullScreen.code(),
      Key::KeyMode => 0x175,
      Key::KeyKeyboard => 0x176,
      Key::KeyAspectRatio => 0x177,
      Key::KeyScreen => Key::KeyAspectRatio.code(),
      Key::KeyPc => 0x178,
      Key::KeyTv => 0x179,
      Key::KeyTv2 => 0x17a,
      Key::KeyVcr => 0x17b,
      Key::KeyVcr2 => 0x17c,
      Key::KeySat => 0x17d,
      Key::KeySat2 => 0x17e,
      Key::KeyCd => 0x17f,
      Key::KeyTape => 0x180,
      Key::KeyRadio => 0x181,
      Key::KeyTuner => 0x182,
      Key::KeyPlayer => 0x183,
      Key::KeyText => 0x184,
      Key::KeyDvd => 0x185,
      Key::KeyAux => 0x186,
      Key::KeyMp3 => 0x187,
      Key::KeyAudio => 0x188,
      Key::KeyVideo => 0x189,
      Key::KeyDirectory => 0x18a,
      Key::KeyList => 0x18b,
      Key::KeyMemo => 0x18c,
      Key::KeyCalendar => 0x18d,
      Key::KeyRed => 0x18e,
      Key::KeyGreen => 0x18f,
      Key::KeyYellow => 0x190,
      Key::KeyBlue => 0x191,
      Key::KeyChannelup => 0x192,
      Key::KeyChanneldown => 0x193,
      Key::KeyFirst => 0x194,
      Key::KeyLast => 0x195,
      Key::KeyAb => 0x196,
      Key::KeyNext => 0x197,
      Key::KeyRestart => 0x198,
      Key::KeySlow => 0x199,
      Key::KeyShuffle => 0x19a,
      Key::KeyBreak => 0x19b,
      Key::KeyPrevious => 0x19c,
      Key::KeyDigits => 0x19d,
      Key::KeyTeen => 0x19e,
      Key::KeyTwen => 0x19f,
      Key::KeyVideophone => 0x1a0,
      Key::KeyGames => 0x1a1,
      Key::KeyZoomin => 0x1a2,
      Key::KeyZoomout => 0x1a3,
      Key::KeyZoomreset => 0x1a4,
      Key::KeyWordprocessor => 0x1a5,
      Key::KeyEditor => 0x1a6,
      Key::KeySpreadsheet => 0x1a7,
      Key::KeyGraphicseditor => 0x1a8,
      Key::KeyPresentation => 0x1a9,
      Key::KeyDatabase => 0x1aa,
      Key::KeyNews => 0x1ab,
      Key::KeyVoicemail => 0x1ac,
      Key::KeyAddressbook => 0x1ad,
      Key::KeyMessenger => 0x1ae,
      Key::KeyDisplaytoggle => 0x1af,
      Key::KeyBrightnessToggle => Key::KeyDisplaytoggle.code(),
      Key::KeySpellcheck => 0x1b0,
      Key::KeyLogoff => 0x1b1,
      Key::KeyDollar => 0x1b2,
      Key::KeyEuro => 0x1b3,
      Key::KeyFrameback => 0x1b4,
      Key::KeyFrameforward => 0x1b5,
      Key::KeyContextMenu => 0x1b6,
      Key::KeyMediaRepeat => 0x1b7,
      Key::Key10channelsup => 0x1b8,
      Key::Key10channelsdown => 0x1b9,
      Key::KeyImages => 0x1ba,
      Key::KeyNotificationCenter => 0x1bc,
      Key::KeyPickupPhone => 0x1bd,
      Key::KeyHangupPhone => 0x1be,
      Key::KeyLinkPhone => 0x1bf,
      Key::KeyDelEol => 0x1c0,
      Key::KeyDelEos => 0x1c1,
      Key::KeyInsLine => 0x1c2,
      Key::KeyDelLine => 0x1c3,
      Key::KeyFn => 0x1d0,
      Key::KeyFnEsc => 0x1d1,
      Key::KeyFnF1 => 0x1d2,
      Key::KeyFnF2 => 0x1d3,
      Key::KeyFnF3 => 0x1d4,
      Key::KeyFnF4 => 0x1d5,
      Key::KeyFnF5 => 0x1d6,
      Key::KeyFnF6 => 0x1d7,
      Key::KeyFnF7 => 0x1d8,
      Key::KeyFnF8 => 0x1d9,
      Key::KeyFnF9 => 0x1da,
      Key::KeyFnF10 => 0x1db,
      Key::KeyFnF11 => 0x1dc,
      Key::KeyFnF12 => 0x1dd,
      Key::KeyFn1 => 0x1de,
      Key::KeyFn2 => 0x1df,
      Key::KeyFnD => 0x1e0,
      Key::KeyFnE => 0x1e1,
      Key::KeyFnF => 0x1e2,
      Key::KeyFnS => 0x1e3,
      Key::KeyFnB => 0x1e4,
      Key::KeyFnRightShift => 0x1e5,
      Key::KeyBrlDot1 => 0x1f1,
      Key::KeyBrlDot2 => 0x1f2,
      Key::KeyBrlDot3 => 0x1f3,
      Key::KeyBrlDot4 => 0x1f4,
      Key::KeyBrlDot5 => 0x1f5,
      Key::KeyBrlDot6 => 0x1f6,
      Key::KeyBrlDot7 => 0x1f7,
      Key::KeyBrlDot8 => 0x1f8,
      Key::KeyBrlDot9 => 0x1f9,
      Key::KeyBrlDot10 => 0x1fa,
      Key::KeyNumeric0 => 0x200,
      Key::KeyNumeric1 => 0x201,
      Key::KeyNumeric2 => 0x202,
      Key::KeyNumeric3 => 0x203,
      Key::KeyNumeric4 => 0x204,
      Key::KeyNumeric5 => 0x205,
      Key::KeyNumeric6 => 0x206,
      Key::KeyNumeric7 => 0x207,
      Key::KeyNumeric8 => 0x208,
      Key::KeyNumeric9 => 0x209,
      Key::KeyNumericStar => 0x20a,
      Key::KeyNumericPound => 0x20b,
      Key::KeyNumericA => 0x20c,
      Key::KeyNumericB => 0x20d,
      Key::KeyNumericC => 0x20e,
      Key::KeyNumericD => 0x20f,
      Key::KeyCameraFocus => 0x210,
      Key::KeyWpsButton => 0x211,
      Key::KeyTouchpadToggle => 0x212,
      Key::KeyTouchpadOn => 0x213,
      Key::KeyTouchpadOff => 0x214,
      Key::KeyCameraZoomin => 0x215,
      Key::KeyCameraZoomout => 0x216,
      Key::KeyCameraUp => 0x217,
      Key::KeyCameraDown => 0x218,
      Key::KeyCameraLeft => 0x219,
      Key::KeyCameraRight => 0x21a,
      Key::KeyAttendantOn => 0x21b,
      Key::KeyAttendantOff => 0x21c,
      Key::KeyAttendantToggle => 0x21d,
      Key::KeyLightsToggle => 0x21e,
      Key::BtnDpadUp => 0x220,
      Key::BtnDpadDown => 0x221,
      Key::BtnDpadLeft => 0x222,
      Key::BtnDpadRight => 0x223,
      Key::BtnGripl => 0x224,
      Key::BtnGripr => 0x225,
      Key::BtnGripl2 => 0x226,
      Key::BtnGripr2 => 0x227,
      Key::KeyAlsToggle => 0x230,
      Key::KeyRotateLockToggle => 0x231,
      Key::KeyRefreshRateToggle => 0x232,
      Key::KeyButtonconfig => 0x240,
      Key::KeyTaskmanager => 0x241,
      Key::KeyJournal => 0x242,
      Key::KeyControlpanel => 0x243,
      Key::KeyAppselect => 0x244,
      Key::KeyScreensaver => 0x245,
      Key::KeyVoicecommand => 0x246,
      Key::KeyAssistant => 0x247,
      Key::KeyKbdLayoutNext => 0x248,
      Key::KeyEmojiPicker => 0x249,
      Key::KeyDictate => 0x24a,
      Key::KeyCameraAccessEnable => 0x24b,
      Key::KeyCameraAccessDisable => 0x24c,
      Key::KeyCameraAccessToggle => 0x24d,
      Key::KeyAccessibility => 0x24e,
      Key::KeyDoNotDisturb => 0x24f,
      Key::KeyBrightnessMin => 0x250,
      Key::KeyBrightnessMax => 0x251,
      Key::KeyEprivacyScreenOn => 0x252,
      Key::KeyEprivacyScreenOff => 0x253,
      Key::KeyActionOnSelection => 0x254,
      Key::KeyContextualInsert => 0x255,
      Key::KeyContextualQuery => 0x256,
      Key::KeyKbdinputassistPrev => 0x260,
      Key::KeyKbdinputassistNext => 0x261,
      Key::KeyKbdinputassistPrevgroup => 0x262,
      Key::KeyKbdinputassistNextgroup => 0x263,
      Key::KeyKbdinputassistAccept => 0x264,
      Key::KeyKbdinputassistCancel => 0x265,
      Key::KeyRightUp => 0x266,
      Key::KeyRightDown => 0x267,
      Key::KeyLeftUp => 0x268,
      Key::KeyLeftDown => 0x269,
      Key::KeyRootMenu => 0x26a,
      Key::KeyMediaTopMenu => 0x26b,
      Key::KeyNumeric11 => 0x26c,
      Key::KeyNumeric12 => 0x26d,
      Key::KeyAudioDesc => 0x26e,
      Key::Key3dMode => 0x26f,
      Key::KeyNextFavorite => 0x270,
      Key::KeyStopRecord => 0x271,
      Key::KeyPauseRecord => 0x272,
      Key::KeyVod => 0x273,
      Key::KeyUnmute => 0x274,
      Key::KeyFastreverse => 0x275,
      Key::KeySlowreverse => 0x276,
      Key::KeyData => 0x277,
      Key::KeyOnscreenKeyboard => 0x278,
      Key::KeyPrivacyScreenToggle => 0x279,
      Key::KeySelectiveScreenshot => 0x27a,
      Key::KeyNextElement => 0x27b,
      Key::KeyPreviousElement => 0x27c,
      Key::KeyAutopilotEngageToggle => 0x27d,
      Key::KeyMarkWaypoint => 0x27e,
      Key::KeySos => 0x27f,
      Key::KeyNavChart => 0x280,
      Key::KeyFishingChart => 0x281,
      Key::KeySingleRangeRadar => 0x282,
      Key::KeyDualRangeRadar => 0x283,
      Key::KeyRadarOverlay => 0x284,
      Key::KeyTraditionalSonar => 0x285,
      Key::KeyClearvuSonar => 0x286,
      Key::KeySidevuSonar => 0x287,
      Key::KeyNavInfo => 0x288,
      Key::KeyBrightnessMenu => 0x289,
      Key::KeyMacro1 => 0x290,
      Key::KeyMacro2 => 0x291,
      Key::KeyMacro3 => 0x292,
      Key::KeyMacro4 => 0x293,
      Key::KeyMacro5 => 0x294,
      Key::KeyMacro6 => 0x295,
      Key::KeyMacro7 => 0x296,
      Key::KeyMacro8 => 0x297,
      Key::KeyMacro9 => 0x298,
      Key::KeyMacro10 => 0x299,
      Key::KeyMacro11 => 0x29a,
      Key::KeyMacro12 => 0x29b,
      Key::KeyMacro13 => 0x29c,
      Key::KeyMacro14 => 0x29d,
      Key::KeyMacro15 => 0x29e,
      Key::KeyMacro16 => 0x29f,
      Key::KeyMacro17 => 0x2a0,
      Key::KeyMacro18 => 0x2a1,
      Key::KeyMacro19 => 0x2a2,
      Key::KeyMacro20 => 0x2a3,
      Key::KeyMacro21 => 0x2a4,
      Key::KeyMacro22 => 0x2a5,
      Key::KeyMacro23 => 0x2a6,
      Key::KeyMacro24 => 0x2a7,
      Key::KeyMacro25 => 0x2a8,
      Key::KeyMacro26 => 0x2a9,
      Key::KeyMacro27 => 0x2aa,
      Key::KeyMacro28 => 0x2ab,
      Key::KeyMacro29 => 0x2ac,
      Key::KeyMacro30 => 0x2ad,
      Key::KeyMacroRecordStart => 0x2b0,
      Key::KeyMacroRecordStop => 0x2b1,
      Key::KeyMacroPresetCycle => 0x2b2,
      Key::KeyMacroPreset1 => 0x2b3,
      Key::KeyMacroPreset2 => 0x2b4,
      Key::KeyMacroPreset3 => 0x2b5,
      Key::KeyKbdLcdMenu1 => 0x2b8,
      Key::KeyKbdLcdMenu2 => 0x2b9,
      Key::KeyKbdLcdMenu3 => 0x2ba,
      Key::KeyKbdLcdMenu4 => 0x2bb,
      Key::KeyKbdLcdMenu5 => 0x2bc,
      Key::KeyPerformance => 0x2bd,
      Key::BtnTriggerHappy => 0x2c0,
      Key::BtnTriggerHappy1 => 0x2c0,
      Key::BtnTriggerHappy2 => 0x2c1,
      Key::BtnTriggerHappy3 => 0x2c2,
      Key::BtnTriggerHappy4 => 0x2c3,
      Key::BtnTriggerHappy5 => 0x2c4,
      Key::BtnTriggerHappy6 => 0x2c5,
      Key::BtnTriggerHappy7 => 0x2c6,
      Key::BtnTriggerHappy8 => 0x2c7,
      Key::BtnTriggerHappy9 => 0x2c8,
      Key::BtnTriggerHappy10 => 0x2c9,
      Key::BtnTriggerHappy11 => 0x2ca,
      Key::BtnTriggerHappy12 => 0x2cb,
      Key::BtnTriggerHappy13 => 0x2cc,
      Key::BtnTriggerHappy14 => 0x2cd,
      Key::BtnTriggerHappy15 => 0x2ce,
      Key::BtnTriggerHappy16 => 0x2cf,
      Key::BtnTriggerHappy17 => 0x2d0,
      Key::BtnTriggerHappy18 => 0x2d1,
      Key::BtnTriggerHappy19 => 0x2d2,
      Key::BtnTriggerHappy20 => 0x2d3,
      Key::BtnTriggerHappy21 => 0x2d4,
      Key::BtnTriggerHappy22 => 0x2d5,
      Key::BtnTriggerHappy23 => 0x2d6,
      Key::BtnTriggerHappy24 => 0x2d7,
      Key::BtnTriggerHappy25 => 0x2d8,
      Key::BtnTriggerHappy26 => 0x2d9,
      Key::BtnTriggerHappy27 => 0x2da,
      Key::BtnTriggerHappy28 => 0x2db,
      Key::BtnTriggerHappy29 => 0x2dc,
      Key::BtnTriggerHappy30 => 0x2dd,
      Key::BtnTriggerHappy31 => 0x2de,
      Key::BtnTriggerHappy32 => 0x2df,
      Key::BtnTriggerHappy33 => 0x2e0,
      Key::BtnTriggerHappy34 => 0x2e1,
      Key::BtnTriggerHappy35 => 0x2e2,
      Key::BtnTriggerHappy36 => 0x2e3,
      Key::BtnTriggerHappy37 => 0x2e4,
      Key::BtnTriggerHappy38 => 0x2e5,
      Key::BtnTriggerHappy39 => 0x2e6,
      Key::BtnTriggerHappy40 => 0x2e7,
      Key::KeyMinInteresting => Key::KeyMute.code(),
      Key::KeyMax => 0x2ff,
      Key::KeyCnt => Key::KeyMax.code() + 1,
    }
  }

  /// The literal name of the constant as it appears in the Linux kernel header.
  pub fn name(&self) -> &'static str {
    match self {
      Key::KeyReserved => "KEY_RESERVED",
      Key::KeyEsc => "KEY_ESC",
      Key::Key1 => "KEY_1",
      Key::Key2 => "KEY_2",
      Key::Key3 => "KEY_3",
      Key::Key4 => "KEY_4",
      Key::Key5 => "KEY_5",
      Key::Key6 => "KEY_6",
      Key::Key7 => "KEY_7",
      Key::Key8 => "KEY_8",
      Key::Key9 => "KEY_9",
      Key::Key0 => "KEY_0",
      Key::KeyMinus => "KEY_MINUS",
      Key::KeyEqual => "KEY_EQUAL",
      Key::KeyBackspace => "KEY_BACKSPACE",
      Key::KeyTab => "KEY_TAB",
      Key::KeyQ => "KEY_Q",
      Key::KeyW => "KEY_W",
      Key::KeyE => "KEY_E",
      Key::KeyR => "KEY_R",
      Key::KeyT => "KEY_T",
      Key::KeyY => "KEY_Y",
      Key::KeyU => "KEY_U",
      Key::KeyI => "KEY_I",
      Key::KeyO => "KEY_O",
      Key::KeyP => "KEY_P",
      Key::KeyLeftbrace => "KEY_LEFTBRACE",
      Key::KeyRightbrace => "KEY_RIGHTBRACE",
      Key::KeyEnter => "KEY_ENTER",
      Key::KeyLeftctrl => "KEY_LEFTCTRL",
      Key::KeyA => "KEY_A",
      Key::KeyS => "KEY_S",
      Key::KeyD => "KEY_D",
      Key::KeyF => "KEY_F",
      Key::KeyG => "KEY_G",
      Key::KeyH => "KEY_H",
      Key::KeyJ => "KEY_J",
      Key::KeyK => "KEY_K",
      Key::KeyL => "KEY_L",
      Key::KeySemicolon => "KEY_SEMICOLON",
      Key::KeyApostrophe => "KEY_APOSTROPHE",
      Key::KeyGrave => "KEY_GRAVE",
      Key::KeyLeftshift => "KEY_LEFTSHIFT",
      Key::KeyBackslash => "KEY_BACKSLASH",
      Key::KeyZ => "KEY_Z",
      Key::KeyX => "KEY_X",
      Key::KeyC => "KEY_C",
      Key::KeyV => "KEY_V",
      Key::KeyB => "KEY_B",
      Key::KeyN => "KEY_N",
      Key::KeyM => "KEY_M",
      Key::KeyComma => "KEY_COMMA",
      Key::KeyDot => "KEY_DOT",
      Key::KeySlash => "KEY_SLASH",
      Key::KeyRightshift => "KEY_RIGHTSHIFT",
      Key::KeyKpasterisk => "KEY_KPASTERISK",
      Key::KeyLeftalt => "KEY_LEFTALT",
      Key::KeySpace => "KEY_SPACE",
      Key::KeyCapslock => "KEY_CAPSLOCK",
      Key::KeyF1 => "KEY_F1",
      Key::KeyF2 => "KEY_F2",
      Key::KeyF3 => "KEY_F3",
      Key::KeyF4 => "KEY_F4",
      Key::KeyF5 => "KEY_F5",
      Key::KeyF6 => "KEY_F6",
      Key::KeyF7 => "KEY_F7",
      Key::KeyF8 => "KEY_F8",
      Key::KeyF9 => "KEY_F9",
      Key::KeyF10 => "KEY_F10",
      Key::KeyNumlock => "KEY_NUMLOCK",
      Key::KeyScrolllock => "KEY_SCROLLLOCK",
      Key::KeyKp7 => "KEY_KP7",
      Key::KeyKp8 => "KEY_KP8",
      Key::KeyKp9 => "KEY_KP9",
      Key::KeyKpminus => "KEY_KPMINUS",
      Key::KeyKp4 => "KEY_KP4",
      Key::KeyKp5 => "KEY_KP5",
      Key::KeyKp6 => "KEY_KP6",
      Key::KeyKpplus => "KEY_KPPLUS",
      Key::KeyKp1 => "KEY_KP1",
      Key::KeyKp2 => "KEY_KP2",
      Key::KeyKp3 => "KEY_KP3",
      Key::KeyKp0 => "KEY_KP0",
      Key::KeyKpdot => "KEY_KPDOT",
      Key::KeyZenkakuhankaku => "KEY_ZENKAKUHANKAKU",
      Key::Key102nd => "KEY_102ND",
      Key::KeyF11 => "KEY_F11",
      Key::KeyF12 => "KEY_F12",
      Key::KeyRo => "KEY_RO",
      Key::KeyKatakana => "KEY_KATAKANA",
      Key::KeyHiragana => "KEY_HIRAGANA",
      Key::KeyHenkan => "KEY_HENKAN",
      Key::KeyKatakanahiragana => "KEY_KATAKANAHIRAGANA",
      Key::KeyMuhenkan => "KEY_MUHENKAN",
      Key::KeyKpjpcomma => "KEY_KPJPCOMMA",
      Key::KeyKpenter => "KEY_KPENTER",
      Key::KeyRightctrl => "KEY_RIGHTCTRL",
      Key::KeyKpslash => "KEY_KPSLASH",
      Key::KeySysrq => "KEY_SYSRQ",
      Key::KeyRightalt => "KEY_RIGHTALT",
      Key::KeyLinefeed => "KEY_LINEFEED",
      Key::KeyHome => "KEY_HOME",
      Key::KeyUp => "KEY_UP",
      Key::KeyPageup => "KEY_PAGEUP",
      Key::KeyLeft => "KEY_LEFT",
      Key::KeyRight => "KEY_RIGHT",
      Key::KeyEnd => "KEY_END",
      Key::KeyDown => "KEY_DOWN",
      Key::KeyPagedown => "KEY_PAGEDOWN",
      Key::KeyInsert => "KEY_INSERT",
      Key::KeyDelete => "KEY_DELETE",
      Key::KeyMacro => "KEY_MACRO",
      Key::KeyMute => "KEY_MUTE",
      Key::KeyVolumedown => "KEY_VOLUMEDOWN",
      Key::KeyVolumeup => "KEY_VOLUMEUP",
      Key::KeyPower => "KEY_POWER",
      Key::KeyKpequal => "KEY_KPEQUAL",
      Key::KeyKpplusminus => "KEY_KPPLUSMINUS",
      Key::KeyPause => "KEY_PAUSE",
      Key::KeyScale => "KEY_SCALE",
      Key::KeyKpcomma => "KEY_KPCOMMA",
      Key::KeyHangeul => "KEY_HANGEUL",
      Key::KeyHanguel => "KEY_HANGUEL",
      Key::KeyHanja => "KEY_HANJA",
      Key::KeyYen => "KEY_YEN",
      Key::KeyLeftmeta => "KEY_LEFTMETA",
      Key::KeyRightmeta => "KEY_RIGHTMETA",
      Key::KeyCompose => "KEY_COMPOSE",
      Key::KeyStop => "KEY_STOP",
      Key::KeyAgain => "KEY_AGAIN",
      Key::KeyProps => "KEY_PROPS",
      Key::KeyUndo => "KEY_UNDO",
      Key::KeyFront => "KEY_FRONT",
      Key::KeyCopy => "KEY_COPY",
      Key::KeyOpen => "KEY_OPEN",
      Key::KeyPaste => "KEY_PASTE",
      Key::KeyFind => "KEY_FIND",
      Key::KeyCut => "KEY_CUT",
      Key::KeyHelp => "KEY_HELP",
      Key::KeyMenu => "KEY_MENU",
      Key::KeyCalc => "KEY_CALC",
      Key::KeySetup => "KEY_SETUP",
      Key::KeySleep => "KEY_SLEEP",
      Key::KeyWakeup => "KEY_WAKEUP",
      Key::KeyFile => "KEY_FILE",
      Key::KeySendfile => "KEY_SENDFILE",
      Key::KeyDeletefile => "KEY_DELETEFILE",
      Key::KeyXfer => "KEY_XFER",
      Key::KeyProg1 => "KEY_PROG1",
      Key::KeyProg2 => "KEY_PROG2",
      Key::KeyWww => "KEY_WWW",
      Key::KeyMsdos => "KEY_MSDOS",
      Key::KeyCoffee => "KEY_COFFEE",
      Key::KeyScreenlock => "KEY_SCREENLOCK",
      Key::KeyRotateDisplay => "KEY_ROTATE_DISPLAY",
      Key::KeyDirection => "KEY_DIRECTION",
      Key::KeyCyclewindows => "KEY_CYCLEWINDOWS",
      Key::KeyMail => "KEY_MAIL",
      Key::KeyBookmarks => "KEY_BOOKMARKS",
      Key::KeyComputer => "KEY_COMPUTER",
      Key::KeyBack => "KEY_BACK",
      Key::KeyForward => "KEY_FORWARD",
      Key::KeyClosecd => "KEY_CLOSECD",
      Key::KeyEjectcd => "KEY_EJECTCD",
      Key::KeyEjectclosecd => "KEY_EJECTCLOSECD",
      Key::KeyNextsong => "KEY_NEXTSONG",
      Key::KeyPlaypause => "KEY_PLAYPAUSE",
      Key::KeyPrevioussong => "KEY_PREVIOUSSONG",
      Key::KeyStopcd => "KEY_STOPCD",
      Key::KeyRecord => "KEY_RECORD",
      Key::KeyRewind => "KEY_REWIND",
      Key::KeyPhone => "KEY_PHONE",
      Key::KeyIso => "KEY_ISO",
      Key::KeyConfig => "KEY_CONFIG",
      Key::KeyHomepage => "KEY_HOMEPAGE",
      Key::KeyRefresh => "KEY_REFRESH",
      Key::KeyExit => "KEY_EXIT",
      Key::KeyMove => "KEY_MOVE",
      Key::KeyEdit => "KEY_EDIT",
      Key::KeyScrollup => "KEY_SCROLLUP",
      Key::KeyScrolldown => "KEY_SCROLLDOWN",
      Key::KeyKpleftparen => "KEY_KPLEFTPAREN",
      Key::KeyKprightparen => "KEY_KPRIGHTPAREN",
      Key::KeyNew => "KEY_NEW",
      Key::KeyRedo => "KEY_REDO",
      Key::KeyF13 => "KEY_F13",
      Key::KeyF14 => "KEY_F14",
      Key::KeyF15 => "KEY_F15",
      Key::KeyF16 => "KEY_F16",
      Key::KeyF17 => "KEY_F17",
      Key::KeyF18 => "KEY_F18",
      Key::KeyF19 => "KEY_F19",
      Key::KeyF20 => "KEY_F20",
      Key::KeyF21 => "KEY_F21",
      Key::KeyF22 => "KEY_F22",
      Key::KeyF23 => "KEY_F23",
      Key::KeyF24 => "KEY_F24",
      Key::KeyPlaycd => "KEY_PLAYCD",
      Key::KeyPausecd => "KEY_PAUSECD",
      Key::KeyProg3 => "KEY_PROG3",
      Key::KeyProg4 => "KEY_PROG4",
      Key::KeyAllApplications => "KEY_ALL_APPLICATIONS",
      Key::KeyDashboard => "KEY_DASHBOARD",
      Key::KeySuspend => "KEY_SUSPEND",
      Key::KeyClose => "KEY_CLOSE",
      Key::KeyPlay => "KEY_PLAY",
      Key::KeyFastforward => "KEY_FASTFORWARD",
      Key::KeyBassboost => "KEY_BASSBOOST",
      Key::KeyPrint => "KEY_PRINT",
      Key::KeyHp => "KEY_HP",
      Key::KeyCamera => "KEY_CAMERA",
      Key::KeySound => "KEY_SOUND",
      Key::KeyQuestion => "KEY_QUESTION",
      Key::KeyEmail => "KEY_EMAIL",
      Key::KeyChat => "KEY_CHAT",
      Key::KeySearch => "KEY_SEARCH",
      Key::KeyConnect => "KEY_CONNECT",
      Key::KeyFinance => "KEY_FINANCE",
      Key::KeySport => "KEY_SPORT",
      Key::KeyShop => "KEY_SHOP",
      Key::KeyAlterase => "KEY_ALTERASE",
      Key::KeyCancel => "KEY_CANCEL",
      Key::KeyBrightnessdown => "KEY_BRIGHTNESSDOWN",
      Key::KeyBrightnessup => "KEY_BRIGHTNESSUP",
      Key::KeyMedia => "KEY_MEDIA",
      Key::KeySwitchvideomode => "KEY_SWITCHVIDEOMODE",
      Key::KeyKbdillumtoggle => "KEY_KBDILLUMTOGGLE",
      Key::KeyKbdillumdown => "KEY_KBDILLUMDOWN",
      Key::KeyKbdillumup => "KEY_KBDILLUMUP",
      Key::KeySend => "KEY_SEND",
      Key::KeyReply => "KEY_REPLY",
      Key::KeyForwardmail => "KEY_FORWARDMAIL",
      Key::KeySave => "KEY_SAVE",
      Key::KeyDocuments => "KEY_DOCUMENTS",
      Key::KeyBattery => "KEY_BATTERY",
      Key::KeyBluetooth => "KEY_BLUETOOTH",
      Key::KeyWlan => "KEY_WLAN",
      Key::KeyUwb => "KEY_UWB",
      Key::KeyUnknown => "KEY_UNKNOWN",
      Key::KeyVideoNext => "KEY_VIDEO_NEXT",
      Key::KeyVideoPrev => "KEY_VIDEO_PREV",
      Key::KeyBrightnessCycle => "KEY_BRIGHTNESS_CYCLE",
      Key::KeyBrightnessAuto => "KEY_BRIGHTNESS_AUTO",
      Key::KeyBrightnessZero => "KEY_BRIGHTNESS_ZERO",
      Key::KeyDisplayOff => "KEY_DISPLAY_OFF",
      Key::KeyWwan => "KEY_WWAN",
      Key::KeyWimax => "KEY_WIMAX",
      Key::KeyRfkill => "KEY_RFKILL",
      Key::KeyMicmute => "KEY_MICMUTE",
      Key::BtnMisc => "BTN_MISC",
      Key::Btn0 => "BTN_0",
      Key::Btn1 => "BTN_1",
      Key::Btn2 => "BTN_2",
      Key::Btn3 => "BTN_3",
      Key::Btn4 => "BTN_4",
      Key::Btn5 => "BTN_5",
      Key::Btn6 => "BTN_6",
      Key::Btn7 => "BTN_7",
      Key::Btn8 => "BTN_8",
      Key::Btn9 => "BTN_9",
      Key::BtnMouse => "BTN_MOUSE",
      Key::BtnLeft => "BTN_LEFT",
      Key::BtnRight => "BTN_RIGHT",
      Key::BtnMiddle => "BTN_MIDDLE",
      Key::BtnSide => "BTN_SIDE",
      Key::BtnExtra => "BTN_EXTRA",
      Key::BtnForward => "BTN_FORWARD",
      Key::BtnBack => "BTN_BACK",
      Key::BtnTask => "BTN_TASK",
      Key::BtnJoystick => "BTN_JOYSTICK",
      Key::BtnTrigger => "BTN_TRIGGER",
      Key::BtnThumb => "BTN_THUMB",
      Key::BtnThumb2 => "BTN_THUMB2",
      Key::BtnTop => "BTN_TOP",
      Key::BtnTop2 => "BTN_TOP2",
      Key::BtnPinkie => "BTN_PINKIE",
      Key::BtnBase => "BTN_BASE",
      Key::BtnBase2 => "BTN_BASE2",
      Key::BtnBase3 => "BTN_BASE3",
      Key::BtnBase4 => "BTN_BASE4",
      Key::BtnBase5 => "BTN_BASE5",
      Key::BtnBase6 => "BTN_BASE6",
      Key::BtnDead => "BTN_DEAD",
      Key::BtnGamepad => "BTN_GAMEPAD",
      Key::BtnSouth => "BTN_SOUTH",
      Key::BtnA => "BTN_A",
      Key::BtnEast => "BTN_EAST",
      Key::BtnB => "BTN_B",
      Key::BtnC => "BTN_C",
      Key::BtnNorth => "BTN_NORTH",
      Key::BtnX => "BTN_X",
      Key::BtnWest => "BTN_WEST",
      Key::BtnY => "BTN_Y",
      Key::BtnZ => "BTN_Z",
      Key::BtnTl => "BTN_TL",
      Key::BtnTr => "BTN_TR",
      Key::BtnTl2 => "BTN_TL2",
      Key::BtnTr2 => "BTN_TR2",
      Key::BtnSelect => "BTN_SELECT",
      Key::BtnStart => "BTN_START",
      Key::BtnMode => "BTN_MODE",
      Key::BtnThumbl => "BTN_THUMBL",
      Key::BtnThumbr => "BTN_THUMBR",
      Key::BtnDigi => "BTN_DIGI",
      Key::BtnToolPen => "BTN_TOOL_PEN",
      Key::BtnToolRubber => "BTN_TOOL_RUBBER",
      Key::BtnToolBrush => "BTN_TOOL_BRUSH",
      Key::BtnToolPencil => "BTN_TOOL_PENCIL",
      Key::BtnToolAirbrush => "BTN_TOOL_AIRBRUSH",
      Key::BtnToolFinger => "BTN_TOOL_FINGER",
      Key::BtnToolMouse => "BTN_TOOL_MOUSE",
      Key::BtnToolLens => "BTN_TOOL_LENS",
      Key::BtnToolQuinttap => "BTN_TOOL_QUINTTAP",
      Key::BtnStylus3 => "BTN_STYLUS3",
      Key::BtnTouch => "BTN_TOUCH",
      Key::BtnStylus => "BTN_STYLUS",
      Key::BtnStylus2 => "BTN_STYLUS2",
      Key::BtnToolDoubletap => "BTN_TOOL_DOUBLETAP",
      Key::BtnToolTripletap => "BTN_TOOL_TRIPLETAP",
      Key::BtnToolQuadtap => "BTN_TOOL_QUADTAP",
      Key::BtnWheel => "BTN_WHEEL",
      Key::BtnGearDown => "BTN_GEAR_DOWN",
      Key::BtnGearUp => "BTN_GEAR_UP",
      Key::KeyOk => "KEY_OK",
      Key::KeySelect => "KEY_SELECT",
      Key::KeyGoto => "KEY_GOTO",
      Key::KeyClear => "KEY_CLEAR",
      Key::KeyPower2 => "KEY_POWER2",
      Key::KeyOption => "KEY_OPTION",
      Key::KeyInfo => "KEY_INFO",
      Key::KeyTime => "KEY_TIME",
      Key::KeyVendor => "KEY_VENDOR",
      Key::KeyArchive => "KEY_ARCHIVE",
      Key::KeyProgram => "KEY_PROGRAM",
      Key::KeyChannel => "KEY_CHANNEL",
      Key::KeyFavorites => "KEY_FAVORITES",
      Key::KeyEpg => "KEY_EPG",
      Key::KeyPvr => "KEY_PVR",
      Key::KeyMhp => "KEY_MHP",
      Key::KeyLanguage => "KEY_LANGUAGE",
      Key::KeyTitle => "KEY_TITLE",
      Key::KeySubtitle => "KEY_SUBTITLE",
      Key::KeyAngle => "KEY_ANGLE",
      Key::KeyFullScreen => "KEY_FULL_SCREEN",
      Key::KeyZoom => "KEY_ZOOM",
      Key::KeyMode => "KEY_MODE",
      Key::KeyKeyboard => "KEY_KEYBOARD",
      Key::KeyAspectRatio => "KEY_ASPECT_RATIO",
      Key::KeyScreen => "KEY_SCREEN",
      Key::KeyPc => "KEY_PC",
      Key::KeyTv => "KEY_TV",
      Key::KeyTv2 => "KEY_TV2",
      Key::KeyVcr => "KEY_VCR",
      Key::KeyVcr2 => "KEY_VCR2",
      Key::KeySat => "KEY_SAT",
      Key::KeySat2 => "KEY_SAT2",
      Key::KeyCd => "KEY_CD",
      Key::KeyTape => "KEY_TAPE",
      Key::KeyRadio => "KEY_RADIO",
      Key::KeyTuner => "KEY_TUNER",
      Key::KeyPlayer => "KEY_PLAYER",
      Key::KeyText => "KEY_TEXT",
      Key::KeyDvd => "KEY_DVD",
      Key::KeyAux => "KEY_AUX",
      Key::KeyMp3 => "KEY_MP3",
      Key::KeyAudio => "KEY_AUDIO",
      Key::KeyVideo => "KEY_VIDEO",
      Key::KeyDirectory => "KEY_DIRECTORY",
      Key::KeyList => "KEY_LIST",
      Key::KeyMemo => "KEY_MEMO",
      Key::KeyCalendar => "KEY_CALENDAR",
      Key::KeyRed => "KEY_RED",
      Key::KeyGreen => "KEY_GREEN",
      Key::KeyYellow => "KEY_YELLOW",
      Key::KeyBlue => "KEY_BLUE",
      Key::KeyChannelup => "KEY_CHANNELUP",
      Key::KeyChanneldown => "KEY_CHANNELDOWN",
      Key::KeyFirst => "KEY_FIRST",
      Key::KeyLast => "KEY_LAST",
      Key::KeyAb => "KEY_AB",
      Key::KeyNext => "KEY_NEXT",
      Key::KeyRestart => "KEY_RESTART",
      Key::KeySlow => "KEY_SLOW",
      Key::KeyShuffle => "KEY_SHUFFLE",
      Key::KeyBreak => "KEY_BREAK",
      Key::KeyPrevious => "KEY_PREVIOUS",
      Key::KeyDigits => "KEY_DIGITS",
      Key::KeyTeen => "KEY_TEEN",
      Key::KeyTwen => "KEY_TWEN",
      Key::KeyVideophone => "KEY_VIDEOPHONE",
      Key::KeyGames => "KEY_GAMES",
      Key::KeyZoomin => "KEY_ZOOMIN",
      Key::KeyZoomout => "KEY_ZOOMOUT",
      Key::KeyZoomreset => "KEY_ZOOMRESET",
      Key::KeyWordprocessor => "KEY_WORDPROCESSOR",
      Key::KeyEditor => "KEY_EDITOR",
      Key::KeySpreadsheet => "KEY_SPREADSHEET",
      Key::KeyGraphicseditor => "KEY_GRAPHICSEDITOR",
      Key::KeyPresentation => "KEY_PRESENTATION",
      Key::KeyDatabase => "KEY_DATABASE",
      Key::KeyNews => "KEY_NEWS",
      Key::KeyVoicemail => "KEY_VOICEMAIL",
      Key::KeyAddressbook => "KEY_ADDRESSBOOK",
      Key::KeyMessenger => "KEY_MESSENGER",
      Key::KeyDisplaytoggle => "KEY_DISPLAYTOGGLE",
      Key::KeyBrightnessToggle => "KEY_BRIGHTNESS_TOGGLE",
      Key::KeySpellcheck => "KEY_SPELLCHECK",
      Key::KeyLogoff => "KEY_LOGOFF",
      Key::KeyDollar => "KEY_DOLLAR",
      Key::KeyEuro => "KEY_EURO",
      Key::KeyFrameback => "KEY_FRAMEBACK",
      Key::KeyFrameforward => "KEY_FRAMEFORWARD",
      Key::KeyContextMenu => "KEY_CONTEXT_MENU",
      Key::KeyMediaRepeat => "KEY_MEDIA_REPEAT",
      Key::Key10channelsup => "KEY_10CHANNELSUP",
      Key::Key10channelsdown => "KEY_10CHANNELSDOWN",
      Key::KeyImages => "KEY_IMAGES",
      Key::KeyNotificationCenter => "KEY_NOTIFICATION_CENTER",
      Key::KeyPickupPhone => "KEY_PICKUP_PHONE",
      Key::KeyHangupPhone => "KEY_HANGUP_PHONE",
      Key::KeyLinkPhone => "KEY_LINK_PHONE",
      Key::KeyDelEol => "KEY_DEL_EOL",
      Key::KeyDelEos => "KEY_DEL_EOS",
      Key::KeyInsLine => "KEY_INS_LINE",
      Key::KeyDelLine => "KEY_DEL_LINE",
      Key::KeyFn => "KEY_FN",
      Key::KeyFnEsc => "KEY_FN_ESC",
      Key::KeyFnF1 => "KEY_FN_F1",
      Key::KeyFnF2 => "KEY_FN_F2",
      Key::KeyFnF3 => "KEY_FN_F3",
      Key::KeyFnF4 => "KEY_FN_F4",
      Key::KeyFnF5 => "KEY_FN_F5",
      Key::KeyFnF6 => "KEY_FN_F6",
      Key::KeyFnF7 => "KEY_FN_F7",
      Key::KeyFnF8 => "KEY_FN_F8",
      Key::KeyFnF9 => "KEY_FN_F9",
      Key::KeyFnF10 => "KEY_FN_F10",
      Key::KeyFnF11 => "KEY_FN_F11",
      Key::KeyFnF12 => "KEY_FN_F12",
      Key::KeyFn1 => "KEY_FN_1",
      Key::KeyFn2 => "KEY_FN_2",
      Key::KeyFnD => "KEY_FN_D",
      Key::KeyFnE => "KEY_FN_E",
      Key::KeyFnF => "KEY_FN_F",
      Key::KeyFnS => "KEY_FN_S",
      Key::KeyFnB => "KEY_FN_B",
      Key::KeyFnRightShift => "KEY_FN_RIGHT_SHIFT",
      Key::KeyBrlDot1 => "KEY_BRL_DOT1",
      Key::KeyBrlDot2 => "KEY_BRL_DOT2",
      Key::KeyBrlDot3 => "KEY_BRL_DOT3",
      Key::KeyBrlDot4 => "KEY_BRL_DOT4",
      Key::KeyBrlDot5 => "KEY_BRL_DOT5",
      Key::KeyBrlDot6 => "KEY_BRL_DOT6",
      Key::KeyBrlDot7 => "KEY_BRL_DOT7",
      Key::KeyBrlDot8 => "KEY_BRL_DOT8",
      Key::KeyBrlDot9 => "KEY_BRL_DOT9",
      Key::KeyBrlDot10 => "KEY_BRL_DOT10",
      Key::KeyNumeric0 => "KEY_NUMERIC_0",
      Key::KeyNumeric1 => "KEY_NUMERIC_1",
      Key::KeyNumeric2 => "KEY_NUMERIC_2",
      Key::KeyNumeric3 => "KEY_NUMERIC_3",
      Key::KeyNumeric4 => "KEY_NUMERIC_4",
      Key::KeyNumeric5 => "KEY_NUMERIC_5",
      Key::KeyNumeric6 => "KEY_NUMERIC_6",
      Key::KeyNumeric7 => "KEY_NUMERIC_7",
      Key::KeyNumeric8 => "KEY_NUMERIC_8",
      Key::KeyNumeric9 => "KEY_NUMERIC_9",
      Key::KeyNumericStar => "KEY_NUMERIC_STAR",
      Key::KeyNumericPound => "KEY_NUMERIC_POUND",
      Key::KeyNumericA => "KEY_NUMERIC_A",
      Key::KeyNumericB => "KEY_NUMERIC_B",
      Key::KeyNumericC => "KEY_NUMERIC_C",
      Key::KeyNumericD => "KEY_NUMERIC_D",
      Key::KeyCameraFocus => "KEY_CAMERA_FOCUS",
      Key::KeyWpsButton => "KEY_WPS_BUTTON",
      Key::KeyTouchpadToggle => "KEY_TOUCHPAD_TOGGLE",
      Key::KeyTouchpadOn => "KEY_TOUCHPAD_ON",
      Key::KeyTouchpadOff => "KEY_TOUCHPAD_OFF",
      Key::KeyCameraZoomin => "KEY_CAMERA_ZOOMIN",
      Key::KeyCameraZoomout => "KEY_CAMERA_ZOOMOUT",
      Key::KeyCameraUp => "KEY_CAMERA_UP",
      Key::KeyCameraDown => "KEY_CAMERA_DOWN",
      Key::KeyCameraLeft => "KEY_CAMERA_LEFT",
      Key::KeyCameraRight => "KEY_CAMERA_RIGHT",
      Key::KeyAttendantOn => "KEY_ATTENDANT_ON",
      Key::KeyAttendantOff => "KEY_ATTENDANT_OFF",
      Key::KeyAttendantToggle => "KEY_ATTENDANT_TOGGLE",
      Key::KeyLightsToggle => "KEY_LIGHTS_TOGGLE",
      Key::BtnDpadUp => "BTN_DPAD_UP",
      Key::BtnDpadDown => "BTN_DPAD_DOWN",
      Key::BtnDpadLeft => "BTN_DPAD_LEFT",
      Key::BtnDpadRight => "BTN_DPAD_RIGHT",
      Key::BtnGripl => "BTN_GRIPL",
      Key::BtnGripr => "BTN_GRIPR",
      Key::BtnGripl2 => "BTN_GRIPL2",
      Key::BtnGripr2 => "BTN_GRIPR2",
      Key::KeyAlsToggle => "KEY_ALS_TOGGLE",
      Key::KeyRotateLockToggle => "KEY_ROTATE_LOCK_TOGGLE",
      Key::KeyRefreshRateToggle => "KEY_REFRESH_RATE_TOGGLE",
      Key::KeyButtonconfig => "KEY_BUTTONCONFIG",
      Key::KeyTaskmanager => "KEY_TASKMANAGER",
      Key::KeyJournal => "KEY_JOURNAL",
      Key::KeyControlpanel => "KEY_CONTROLPANEL",
      Key::KeyAppselect => "KEY_APPSELECT",
      Key::KeyScreensaver => "KEY_SCREENSAVER",
      Key::KeyVoicecommand => "KEY_VOICECOMMAND",
      Key::KeyAssistant => "KEY_ASSISTANT",
      Key::KeyKbdLayoutNext => "KEY_KBD_LAYOUT_NEXT",
      Key::KeyEmojiPicker => "KEY_EMOJI_PICKER",
      Key::KeyDictate => "KEY_DICTATE",
      Key::KeyCameraAccessEnable => "KEY_CAMERA_ACCESS_ENABLE",
      Key::KeyCameraAccessDisable => "KEY_CAMERA_ACCESS_DISABLE",
      Key::KeyCameraAccessToggle => "KEY_CAMERA_ACCESS_TOGGLE",
      Key::KeyAccessibility => "KEY_ACCESSIBILITY",
      Key::KeyDoNotDisturb => "KEY_DO_NOT_DISTURB",
      Key::KeyBrightnessMin => "KEY_BRIGHTNESS_MIN",
      Key::KeyBrightnessMax => "KEY_BRIGHTNESS_MAX",
      Key::KeyEprivacyScreenOn => "KEY_EPRIVACY_SCREEN_ON",
      Key::KeyEprivacyScreenOff => "KEY_EPRIVACY_SCREEN_OFF",
      Key::KeyActionOnSelection => "KEY_ACTION_ON_SELECTION",
      Key::KeyContextualInsert => "KEY_CONTEXTUAL_INSERT",
      Key::KeyContextualQuery => "KEY_CONTEXTUAL_QUERY",
      Key::KeyKbdinputassistPrev => "KEY_KBDINPUTASSIST_PREV",
      Key::KeyKbdinputassistNext => "KEY_KBDINPUTASSIST_NEXT",
      Key::KeyKbdinputassistPrevgroup => "KEY_KBDINPUTASSIST_PREVGROUP",
      Key::KeyKbdinputassistNextgroup => "KEY_KBDINPUTASSIST_NEXTGROUP",
      Key::KeyKbdinputassistAccept => "KEY_KBDINPUTASSIST_ACCEPT",
      Key::KeyKbdinputassistCancel => "KEY_KBDINPUTASSIST_CANCEL",
      Key::KeyRightUp => "KEY_RIGHT_UP",
      Key::KeyRightDown => "KEY_RIGHT_DOWN",
      Key::KeyLeftUp => "KEY_LEFT_UP",
      Key::KeyLeftDown => "KEY_LEFT_DOWN",
      Key::KeyRootMenu => "KEY_ROOT_MENU",
      Key::KeyMediaTopMenu => "KEY_MEDIA_TOP_MENU",
      Key::KeyNumeric11 => "KEY_NUMERIC_11",
      Key::KeyNumeric12 => "KEY_NUMERIC_12",
      Key::KeyAudioDesc => "KEY_AUDIO_DESC",
      Key::Key3dMode => "KEY_3D_MODE",
      Key::KeyNextFavorite => "KEY_NEXT_FAVORITE",
      Key::KeyStopRecord => "KEY_STOP_RECORD",
      Key::KeyPauseRecord => "KEY_PAUSE_RECORD",
      Key::KeyVod => "KEY_VOD",
      Key::KeyUnmute => "KEY_UNMUTE",
      Key::KeyFastreverse => "KEY_FASTREVERSE",
      Key::KeySlowreverse => "KEY_SLOWREVERSE",
      Key::KeyData => "KEY_DATA",
      Key::KeyOnscreenKeyboard => "KEY_ONSCREEN_KEYBOARD",
      Key::KeyPrivacyScreenToggle => "KEY_PRIVACY_SCREEN_TOGGLE",
      Key::KeySelectiveScreenshot => "KEY_SELECTIVE_SCREENSHOT",
      Key::KeyNextElement => "KEY_NEXT_ELEMENT",
      Key::KeyPreviousElement => "KEY_PREVIOUS_ELEMENT",
      Key::KeyAutopilotEngageToggle => "KEY_AUTOPILOT_ENGAGE_TOGGLE",
      Key::KeyMarkWaypoint => "KEY_MARK_WAYPOINT",
      Key::KeySos => "KEY_SOS",
      Key::KeyNavChart => "KEY_NAV_CHART",
      Key::KeyFishingChart => "KEY_FISHING_CHART",
      Key::KeySingleRangeRadar => "KEY_SINGLE_RANGE_RADAR",
      Key::KeyDualRangeRadar => "KEY_DUAL_RANGE_RADAR",
      Key::KeyRadarOverlay => "KEY_RADAR_OVERLAY",
      Key::KeyTraditionalSonar => "KEY_TRADITIONAL_SONAR",
      Key::KeyClearvuSonar => "KEY_CLEARVU_SONAR",
      Key::KeySidevuSonar => "KEY_SIDEVU_SONAR",
      Key::KeyNavInfo => "KEY_NAV_INFO",
      Key::KeyBrightnessMenu => "KEY_BRIGHTNESS_MENU",
      Key::KeyMacro1 => "KEY_MACRO1",
      Key::KeyMacro2 => "KEY_MACRO2",
      Key::KeyMacro3 => "KEY_MACRO3",
      Key::KeyMacro4 => "KEY_MACRO4",
      Key::KeyMacro5 => "KEY_MACRO5",
      Key::KeyMacro6 => "KEY_MACRO6",
      Key::KeyMacro7 => "KEY_MACRO7",
      Key::KeyMacro8 => "KEY_MACRO8",
      Key::KeyMacro9 => "KEY_MACRO9",
      Key::KeyMacro10 => "KEY_MACRO10",
      Key::KeyMacro11 => "KEY_MACRO11",
      Key::KeyMacro12 => "KEY_MACRO12",
      Key::KeyMacro13 => "KEY_MACRO13",
      Key::KeyMacro14 => "KEY_MACRO14",
      Key::KeyMacro15 => "KEY_MACRO15",
      Key::KeyMacro16 => "KEY_MACRO16",
      Key::KeyMacro17 => "KEY_MACRO17",
      Key::KeyMacro18 => "KEY_MACRO18",
      Key::KeyMacro19 => "KEY_MACRO19",
      Key::KeyMacro20 => "KEY_MACRO20",
      Key::KeyMacro21 => "KEY_MACRO21",
      Key::KeyMacro22 => "KEY_MACRO22",
      Key::KeyMacro23 => "KEY_MACRO23",
      Key::KeyMacro24 => "KEY_MACRO24",
      Key::KeyMacro25 => "KEY_MACRO25",
      Key::KeyMacro26 => "KEY_MACRO26",
      Key::KeyMacro27 => "KEY_MACRO27",
      Key::KeyMacro28 => "KEY_MACRO28",
      Key::KeyMacro29 => "KEY_MACRO29",
      Key::KeyMacro30 => "KEY_MACRO30",
      Key::KeyMacroRecordStart => "KEY_MACRO_RECORD_START",
      Key::KeyMacroRecordStop => "KEY_MACRO_RECORD_STOP",
      Key::KeyMacroPresetCycle => "KEY_MACRO_PRESET_CYCLE",
      Key::KeyMacroPreset1 => "KEY_MACRO_PRESET1",
      Key::KeyMacroPreset2 => "KEY_MACRO_PRESET2",
      Key::KeyMacroPreset3 => "KEY_MACRO_PRESET3",
      Key::KeyKbdLcdMenu1 => "KEY_KBD_LCD_MENU1",
      Key::KeyKbdLcdMenu2 => "KEY_KBD_LCD_MENU2",
      Key::KeyKbdLcdMenu3 => "KEY_KBD_LCD_MENU3",
      Key::KeyKbdLcdMenu4 => "KEY_KBD_LCD_MENU4",
      Key::KeyKbdLcdMenu5 => "KEY_KBD_LCD_MENU5",
      Key::KeyPerformance => "KEY_PERFORMANCE",
      Key::BtnTriggerHappy => "BTN_TRIGGER_HAPPY",
      Key::BtnTriggerHappy1 => "BTN_TRIGGER_HAPPY1",
      Key::BtnTriggerHappy2 => "BTN_TRIGGER_HAPPY2",
      Key::BtnTriggerHappy3 => "BTN_TRIGGER_HAPPY3",
      Key::BtnTriggerHappy4 => "BTN_TRIGGER_HAPPY4",
      Key::BtnTriggerHappy5 => "BTN_TRIGGER_HAPPY5",
      Key::BtnTriggerHappy6 => "BTN_TRIGGER_HAPPY6",
      Key::BtnTriggerHappy7 => "BTN_TRIGGER_HAPPY7",
      Key::BtnTriggerHappy8 => "BTN_TRIGGER_HAPPY8",
      Key::BtnTriggerHappy9 => "BTN_TRIGGER_HAPPY9",
      Key::BtnTriggerHappy10 => "BTN_TRIGGER_HAPPY10",
      Key::BtnTriggerHappy11 => "BTN_TRIGGER_HAPPY11",
      Key::BtnTriggerHappy12 => "BTN_TRIGGER_HAPPY12",
      Key::BtnTriggerHappy13 => "BTN_TRIGGER_HAPPY13",
      Key::BtnTriggerHappy14 => "BTN_TRIGGER_HAPPY14",
      Key::BtnTriggerHappy15 => "BTN_TRIGGER_HAPPY15",
      Key::BtnTriggerHappy16 => "BTN_TRIGGER_HAPPY16",
      Key::BtnTriggerHappy17 => "BTN_TRIGGER_HAPPY17",
      Key::BtnTriggerHappy18 => "BTN_TRIGGER_HAPPY18",
      Key::BtnTriggerHappy19 => "BTN_TRIGGER_HAPPY19",
      Key::BtnTriggerHappy20 => "BTN_TRIGGER_HAPPY20",
      Key::BtnTriggerHappy21 => "BTN_TRIGGER_HAPPY21",
      Key::BtnTriggerHappy22 => "BTN_TRIGGER_HAPPY22",
      Key::BtnTriggerHappy23 => "BTN_TRIGGER_HAPPY23",
      Key::BtnTriggerHappy24 => "BTN_TRIGGER_HAPPY24",
      Key::BtnTriggerHappy25 => "BTN_TRIGGER_HAPPY25",
      Key::BtnTriggerHappy26 => "BTN_TRIGGER_HAPPY26",
      Key::BtnTriggerHappy27 => "BTN_TRIGGER_HAPPY27",
      Key::BtnTriggerHappy28 => "BTN_TRIGGER_HAPPY28",
      Key::BtnTriggerHappy29 => "BTN_TRIGGER_HAPPY29",
      Key::BtnTriggerHappy30 => "BTN_TRIGGER_HAPPY30",
      Key::BtnTriggerHappy31 => "BTN_TRIGGER_HAPPY31",
      Key::BtnTriggerHappy32 => "BTN_TRIGGER_HAPPY32",
      Key::BtnTriggerHappy33 => "BTN_TRIGGER_HAPPY33",
      Key::BtnTriggerHappy34 => "BTN_TRIGGER_HAPPY34",
      Key::BtnTriggerHappy35 => "BTN_TRIGGER_HAPPY35",
      Key::BtnTriggerHappy36 => "BTN_TRIGGER_HAPPY36",
      Key::BtnTriggerHappy37 => "BTN_TRIGGER_HAPPY37",
      Key::BtnTriggerHappy38 => "BTN_TRIGGER_HAPPY38",
      Key::BtnTriggerHappy39 => "BTN_TRIGGER_HAPPY39",
      Key::BtnTriggerHappy40 => "BTN_TRIGGER_HAPPY40",
      Key::KeyMinInteresting => "KEY_MIN_INTERESTING",
      Key::KeyMax => "KEY_MAX",
      Key::KeyCnt => "KEY_CNT",
    }
  }
}

impl Key {
  /// The printable character this key represents on a standard US QWERTY
  /// layout, for keys that have a visual representation (letters, digits,
  /// and the common punctuation keys). Letters are reported uppercase;
  /// the key itself doesn't know about shift state, only its label.
  /// Keys with no glyph of their own, like `KeyLeftctrl` or `KeyF1`,
  /// return `None`.
  pub fn as_char(&self) -> Option<char> {
    Some(match self {
      Key::KeyA => 'A',
      Key::KeyB => 'B',
      Key::KeyC => 'C',
      Key::KeyD => 'D',
      Key::KeyE => 'E',
      Key::KeyF => 'F',
      Key::KeyG => 'G',
      Key::KeyH => 'H',
      Key::KeyI => 'I',
      Key::KeyJ => 'J',
      Key::KeyK => 'K',
      Key::KeyL => 'L',
      Key::KeyM => 'M',
      Key::KeyN => 'N',
      Key::KeyO => 'O',
      Key::KeyP => 'P',
      Key::KeyQ => 'Q',
      Key::KeyR => 'R',
      Key::KeyS => 'S',
      Key::KeyT => 'T',
      Key::KeyU => 'U',
      Key::KeyV => 'V',
      Key::KeyW => 'W',
      Key::KeyX => 'X',
      Key::KeyY => 'Y',
      Key::KeyZ => 'Z',
      Key::Key0 => '0',
      Key::Key1 => '1',
      Key::Key2 => '2',
      Key::Key3 => '3',
      Key::Key4 => '4',
      Key::Key5 => '5',
      Key::Key6 => '6',
      Key::Key7 => '7',
      Key::Key8 => '8',
      Key::Key9 => '9',
      Key::KeyMinus => '-',
      Key::KeyEqual => '=',
      Key::KeyLeftbrace => '[',
      Key::KeyRightbrace => ']',
      Key::KeySemicolon => ';',
      Key::KeyApostrophe => '\'',
      Key::KeyGrave => '`',
      Key::KeyBackslash => '\\',
      Key::KeyComma => ',',
      Key::KeyDot => '.',
      Key::KeySlash => '/',
      Key::KeySpace => ' ',
      _ => return None,
    })
  }

  /// The reverse of [`Key::as_char`]: looks up the key that produces a
  /// given printable character. Letters are matched case-insensitively,
  /// since `'K'` and `'k'` are the same physical key, just with a
  /// different shift state. Returns `None` if no key on this list has
  /// that glyph.
  pub fn from_char(c: char) -> Option<Key> {
    Some(match c.to_ascii_uppercase() {
      'A' => Key::KeyA,
      'B' => Key::KeyB,
      'C' => Key::KeyC,
      'D' => Key::KeyD,
      'E' => Key::KeyE,
      'F' => Key::KeyF,
      'G' => Key::KeyG,
      'H' => Key::KeyH,
      'I' => Key::KeyI,
      'J' => Key::KeyJ,
      'K' => Key::KeyK,
      'L' => Key::KeyL,
      'M' => Key::KeyM,
      'N' => Key::KeyN,
      'O' => Key::KeyO,
      'P' => Key::KeyP,
      'Q' => Key::KeyQ,
      'R' => Key::KeyR,
      'S' => Key::KeyS,
      'T' => Key::KeyT,
      'U' => Key::KeyU,
      'V' => Key::KeyV,
      'W' => Key::KeyW,
      'X' => Key::KeyX,
      'Y' => Key::KeyY,
      'Z' => Key::KeyZ,
      '0' => Key::Key0,
      '1' => Key::Key1,
      '2' => Key::Key2,
      '3' => Key::Key3,
      '4' => Key::Key4,
      '5' => Key::Key5,
      '6' => Key::Key6,
      '7' => Key::Key7,
      '8' => Key::Key8,
      '9' => Key::Key9,
      '-' => Key::KeyMinus,
      '=' => Key::KeyEqual,
      '[' => Key::KeyLeftbrace,
      ']' => Key::KeyRightbrace,
      ';' => Key::KeySemicolon,
      '\'' => Key::KeyApostrophe,
      '`' => Key::KeyGrave,
      '\\' => Key::KeyBackslash,
      ',' => Key::KeyComma,
      '.' => Key::KeyDot,
      '/' => Key::KeySlash,
      ' ' => Key::KeySpace,
      _ => return None,
    })
  }
}

/// Relative axes
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum RelativeAxis {
  RelX,
  RelY,
  RelZ,
  RelRx,
  RelRy,
  RelRz,
  RelHwheel,
  RelDial,
  RelWheel,
  RelMisc,
  // 0x0a is reserved and should not be used in input drivers.
  // It was used by HID as REL_MISC+1 and userspace needs to detect if
  // the next REL_* event is correct or is just REL_MISC + n.
  // We define here REL_RESERVED so userspace can rely on it and detect
  // the situation described above.
  RelReserved,
  RelWheelHiRes,
  RelHwheelHiRes,
  RelMax,
  RelCnt,
}

impl RelativeAxis {
  /// The raw numeric event code, as defined by the Linux kernel.
  pub fn code(&self) -> u32 {
    match self {
      RelativeAxis::RelX => 0x00,
      RelativeAxis::RelY => 0x01,
      RelativeAxis::RelZ => 0x02,
      RelativeAxis::RelRx => 0x03,
      RelativeAxis::RelRy => 0x04,
      RelativeAxis::RelRz => 0x05,
      RelativeAxis::RelHwheel => 0x06,
      RelativeAxis::RelDial => 0x07,
      RelativeAxis::RelWheel => 0x08,
      RelativeAxis::RelMisc => 0x09,
      RelativeAxis::RelReserved => 0x0a,
      RelativeAxis::RelWheelHiRes => 0x0b,
      RelativeAxis::RelHwheelHiRes => 0x0c,
      RelativeAxis::RelMax => 0x0f,
      RelativeAxis::RelCnt => RelativeAxis::RelMax.code() + 1,
    }
  }

  /// The literal name of the constant as it appears in the Linux kernel header.
  pub fn name(&self) -> &'static str {
    match self {
      RelativeAxis::RelX => "REL_X",
      RelativeAxis::RelY => "REL_Y",
      RelativeAxis::RelZ => "REL_Z",
      RelativeAxis::RelRx => "REL_RX",
      RelativeAxis::RelRy => "REL_RY",
      RelativeAxis::RelRz => "REL_RZ",
      RelativeAxis::RelHwheel => "REL_HWHEEL",
      RelativeAxis::RelDial => "REL_DIAL",
      RelativeAxis::RelWheel => "REL_WHEEL",
      RelativeAxis::RelMisc => "REL_MISC",
      RelativeAxis::RelReserved => "REL_RESERVED",
      RelativeAxis::RelWheelHiRes => "REL_WHEEL_HI_RES",
      RelativeAxis::RelHwheelHiRes => "REL_HWHEEL_HI_RES",
      RelativeAxis::RelMax => "REL_MAX",
      RelativeAxis::RelCnt => "REL_CNT",
    }
  }
}

/// Absolute axes
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum AbsoluteAxis {
  AbsX,
  AbsY,
  AbsZ,
  AbsRx,
  AbsRy,
  AbsRz,
  AbsThrottle,
  AbsRudder,
  AbsWheel,
  AbsGas,
  AbsBrake,
  AbsHat0x,
  AbsHat0y,
  AbsHat1x,
  AbsHat1y,
  AbsHat2x,
  AbsHat2y,
  AbsHat3x,
  AbsHat3y,
  AbsPressure,
  AbsDistance,
  AbsTiltX,
  AbsTiltY,
  AbsToolWidth,

  AbsVolume,
  AbsProfile,
  AbsSndProfile,

  AbsMisc,

  // 0x2e is reserved and should not be used in input drivers.
  // It was used by HID as ABS_MISC+6 and userspace needs to detect if
  // the next ABS_* event is correct or is just ABS_MISC + n.
  // We define here ABS_RESERVED so userspace can rely on it and detect
  // the situation described above.
  AbsReserved,

  /// MT slot being modified
  AbsMtSlot,
  /// Major axis of touching ellipse
  AbsMtTouchMajor,
  /// Minor axis (omit if circular)
  AbsMtTouchMinor,
  /// Major axis of approaching ellipse
  AbsMtWidthMajor,
  /// Minor axis (omit if circular)
  AbsMtWidthMinor,
  /// Ellipse orientation
  AbsMtOrientation,
  /// Center X touch position
  AbsMtPositionX,
  /// Center Y touch position
  AbsMtPositionY,
  /// Type of touching device
  AbsMtToolType,
  /// Group a set of packets as a blob
  AbsMtBlobId,
  /// Unique ID of initiated contact
  AbsMtTrackingId,
  /// Pressure on contact area
  AbsMtPressure,
  /// Contact hover distance
  AbsMtDistance,
  /// Center X tool position
  AbsMtToolX,
  /// Center Y tool position
  AbsMtToolY,

  AbsMax,
  AbsCnt,
}

impl AbsoluteAxis {
  /// The raw numeric event code, as defined by the Linux kernel.
  pub fn code(&self) -> u32 {
    match self {
      AbsoluteAxis::AbsX => 0x00,
      AbsoluteAxis::AbsY => 0x01,
      AbsoluteAxis::AbsZ => 0x02,
      AbsoluteAxis::AbsRx => 0x03,
      AbsoluteAxis::AbsRy => 0x04,
      AbsoluteAxis::AbsRz => 0x05,
      AbsoluteAxis::AbsThrottle => 0x06,
      AbsoluteAxis::AbsRudder => 0x07,
      AbsoluteAxis::AbsWheel => 0x08,
      AbsoluteAxis::AbsGas => 0x09,
      AbsoluteAxis::AbsBrake => 0x0a,
      AbsoluteAxis::AbsHat0x => 0x10,
      AbsoluteAxis::AbsHat0y => 0x11,
      AbsoluteAxis::AbsHat1x => 0x12,
      AbsoluteAxis::AbsHat1y => 0x13,
      AbsoluteAxis::AbsHat2x => 0x14,
      AbsoluteAxis::AbsHat2y => 0x15,
      AbsoluteAxis::AbsHat3x => 0x16,
      AbsoluteAxis::AbsHat3y => 0x17,
      AbsoluteAxis::AbsPressure => 0x18,
      AbsoluteAxis::AbsDistance => 0x19,
      AbsoluteAxis::AbsTiltX => 0x1a,
      AbsoluteAxis::AbsTiltY => 0x1b,
      AbsoluteAxis::AbsToolWidth => 0x1c,
      AbsoluteAxis::AbsVolume => 0x20,
      AbsoluteAxis::AbsProfile => 0x21,
      AbsoluteAxis::AbsSndProfile => 0x22,
      AbsoluteAxis::AbsMisc => 0x28,
      AbsoluteAxis::AbsReserved => 0x2e,
      AbsoluteAxis::AbsMtSlot => 0x2f,
      AbsoluteAxis::AbsMtTouchMajor => 0x30,
      AbsoluteAxis::AbsMtTouchMinor => 0x31,
      AbsoluteAxis::AbsMtWidthMajor => 0x32,
      AbsoluteAxis::AbsMtWidthMinor => 0x33,
      AbsoluteAxis::AbsMtOrientation => 0x34,
      AbsoluteAxis::AbsMtPositionX => 0x35,
      AbsoluteAxis::AbsMtPositionY => 0x36,
      AbsoluteAxis::AbsMtToolType => 0x37,
      AbsoluteAxis::AbsMtBlobId => 0x38,
      AbsoluteAxis::AbsMtTrackingId => 0x39,
      AbsoluteAxis::AbsMtPressure => 0x3a,
      AbsoluteAxis::AbsMtDistance => 0x3b,
      AbsoluteAxis::AbsMtToolX => 0x3c,
      AbsoluteAxis::AbsMtToolY => 0x3d,
      AbsoluteAxis::AbsMax => 0x3f,
      AbsoluteAxis::AbsCnt => AbsoluteAxis::AbsMax.code() + 1,
    }
  }

  /// The literal name of the constant as it appears in the Linux kernel header.
  pub fn name(&self) -> &'static str {
    match self {
      AbsoluteAxis::AbsX => "ABS_X",
      AbsoluteAxis::AbsY => "ABS_Y",
      AbsoluteAxis::AbsZ => "ABS_Z",
      AbsoluteAxis::AbsRx => "ABS_RX",
      AbsoluteAxis::AbsRy => "ABS_RY",
      AbsoluteAxis::AbsRz => "ABS_RZ",
      AbsoluteAxis::AbsThrottle => "ABS_THROTTLE",
      AbsoluteAxis::AbsRudder => "ABS_RUDDER",
      AbsoluteAxis::AbsWheel => "ABS_WHEEL",
      AbsoluteAxis::AbsGas => "ABS_GAS",
      AbsoluteAxis::AbsBrake => "ABS_BRAKE",
      AbsoluteAxis::AbsHat0x => "ABS_HAT0X",
      AbsoluteAxis::AbsHat0y => "ABS_HAT0Y",
      AbsoluteAxis::AbsHat1x => "ABS_HAT1X",
      AbsoluteAxis::AbsHat1y => "ABS_HAT1Y",
      AbsoluteAxis::AbsHat2x => "ABS_HAT2X",
      AbsoluteAxis::AbsHat2y => "ABS_HAT2Y",
      AbsoluteAxis::AbsHat3x => "ABS_HAT3X",
      AbsoluteAxis::AbsHat3y => "ABS_HAT3Y",
      AbsoluteAxis::AbsPressure => "ABS_PRESSURE",
      AbsoluteAxis::AbsDistance => "ABS_DISTANCE",
      AbsoluteAxis::AbsTiltX => "ABS_TILT_X",
      AbsoluteAxis::AbsTiltY => "ABS_TILT_Y",
      AbsoluteAxis::AbsToolWidth => "ABS_TOOL_WIDTH",
      AbsoluteAxis::AbsVolume => "ABS_VOLUME",
      AbsoluteAxis::AbsProfile => "ABS_PROFILE",
      AbsoluteAxis::AbsSndProfile => "ABS_SND_PROFILE",
      AbsoluteAxis::AbsMisc => "ABS_MISC",
      AbsoluteAxis::AbsReserved => "ABS_RESERVED",
      AbsoluteAxis::AbsMtSlot => "ABS_MT_SLOT",
      AbsoluteAxis::AbsMtTouchMajor => "ABS_MT_TOUCH_MAJOR",
      AbsoluteAxis::AbsMtTouchMinor => "ABS_MT_TOUCH_MINOR",
      AbsoluteAxis::AbsMtWidthMajor => "ABS_MT_WIDTH_MAJOR",
      AbsoluteAxis::AbsMtWidthMinor => "ABS_MT_WIDTH_MINOR",
      AbsoluteAxis::AbsMtOrientation => "ABS_MT_ORIENTATION",
      AbsoluteAxis::AbsMtPositionX => "ABS_MT_POSITION_X",
      AbsoluteAxis::AbsMtPositionY => "ABS_MT_POSITION_Y",
      AbsoluteAxis::AbsMtToolType => "ABS_MT_TOOL_TYPE",
      AbsoluteAxis::AbsMtBlobId => "ABS_MT_BLOB_ID",
      AbsoluteAxis::AbsMtTrackingId => "ABS_MT_TRACKING_ID",
      AbsoluteAxis::AbsMtPressure => "ABS_MT_PRESSURE",
      AbsoluteAxis::AbsMtDistance => "ABS_MT_DISTANCE",
      AbsoluteAxis::AbsMtToolX => "ABS_MT_TOOL_X",
      AbsoluteAxis::AbsMtToolY => "ABS_MT_TOOL_Y",
      AbsoluteAxis::AbsMax => "ABS_MAX",
      AbsoluteAxis::AbsCnt => "ABS_CNT",
    }
  }
}

/// Switch events
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum SwitchEvent {
  /// set = lid shut
  SwLid,
  /// set = tablet mode
  SwTabletMode,
  /// set = inserted
  SwHeadphoneInsert,
  /// rfkill master switch, type "any" set = radio enabled
  SwRfkillAll,
  /// deprecated
  SwRadio,
  /// set = inserted
  SwMicrophoneInsert,
  /// set = plugged into dock
  SwDock,
  /// set = inserted
  SwLineoutInsert,
  /// set = mechanical switch set
  SwJackPhysicalInsert,
  /// set = inserted
  SwVideooutInsert,
  /// set = lens covered
  SwCameraLensCover,
  /// set = keypad slide out
  SwKeypadSlide,
  /// set = front proximity sensor active
  SwFrontProximity,
  /// set = rotate locked/disabled
  SwRotateLock,
  /// set = inserted
  SwLineinInsert,
  /// set = device disabled
  SwMuteDevice,
  /// set = pen inserted
  SwPenInserted,
  /// set = cover closed
  SwMachineCover,
  /// set = USB audio device connected
  SwUsbInsert,
  SwMax,
  SwCnt,
}

impl SwitchEvent {
  /// The raw numeric event code, as defined by the Linux kernel.
  pub fn code(&self) -> u32 {
    match self {
      SwitchEvent::SwLid => 0x00,
      SwitchEvent::SwTabletMode => 0x01,
      SwitchEvent::SwHeadphoneInsert => 0x02,
      SwitchEvent::SwRfkillAll => 0x03,
      SwitchEvent::SwRadio => SwitchEvent::SwRfkillAll.code(),
      SwitchEvent::SwMicrophoneInsert => 0x04,
      SwitchEvent::SwDock => 0x05,
      SwitchEvent::SwLineoutInsert => 0x06,
      SwitchEvent::SwJackPhysicalInsert => 0x07,
      SwitchEvent::SwVideooutInsert => 0x08,
      SwitchEvent::SwCameraLensCover => 0x09,
      SwitchEvent::SwKeypadSlide => 0x0a,
      SwitchEvent::SwFrontProximity => 0x0b,
      SwitchEvent::SwRotateLock => 0x0c,
      SwitchEvent::SwLineinInsert => 0x0d,
      SwitchEvent::SwMuteDevice => 0x0e,
      SwitchEvent::SwPenInserted => 0x0f,
      SwitchEvent::SwMachineCover => 0x10,
      SwitchEvent::SwUsbInsert => 0x11,
      SwitchEvent::SwMax => 0x11,
      SwitchEvent::SwCnt => SwitchEvent::SwMax.code() + 1,
    }
  }

  /// The literal name of the constant as it appears in the Linux kernel header.
  pub fn name(&self) -> &'static str {
    match self {
      SwitchEvent::SwLid => "SW_LID",
      SwitchEvent::SwTabletMode => "SW_TABLET_MODE",
      SwitchEvent::SwHeadphoneInsert => "SW_HEADPHONE_INSERT",
      SwitchEvent::SwRfkillAll => "SW_RFKILL_ALL",
      SwitchEvent::SwRadio => "SW_RADIO",
      SwitchEvent::SwMicrophoneInsert => "SW_MICROPHONE_INSERT",
      SwitchEvent::SwDock => "SW_DOCK",
      SwitchEvent::SwLineoutInsert => "SW_LINEOUT_INSERT",
      SwitchEvent::SwJackPhysicalInsert => "SW_JACK_PHYSICAL_INSERT",
      SwitchEvent::SwVideooutInsert => "SW_VIDEOOUT_INSERT",
      SwitchEvent::SwCameraLensCover => "SW_CAMERA_LENS_COVER",
      SwitchEvent::SwKeypadSlide => "SW_KEYPAD_SLIDE",
      SwitchEvent::SwFrontProximity => "SW_FRONT_PROXIMITY",
      SwitchEvent::SwRotateLock => "SW_ROTATE_LOCK",
      SwitchEvent::SwLineinInsert => "SW_LINEIN_INSERT",
      SwitchEvent::SwMuteDevice => "SW_MUTE_DEVICE",
      SwitchEvent::SwPenInserted => "SW_PEN_INSERTED",
      SwitchEvent::SwMachineCover => "SW_MACHINE_COVER",
      SwitchEvent::SwUsbInsert => "SW_USB_INSERT",
      SwitchEvent::SwMax => "SW_MAX",
      SwitchEvent::SwCnt => "SW_CNT",
    }
  }
}

/// Misc events
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum Misc {
  MscSerial,
  MscPulseled,
  MscGesture,
  MscRaw,
  MscScan,
  MscTimestamp,
  MscMax,
  MscCnt,
}

impl Misc {
  /// The raw numeric event code, as defined by the Linux kernel.
  pub fn code(&self) -> u32 {
    match self {
      Misc::MscSerial => 0x00,
      Misc::MscPulseled => 0x01,
      Misc::MscGesture => 0x02,
      Misc::MscRaw => 0x03,
      Misc::MscScan => 0x04,
      Misc::MscTimestamp => 0x05,
      Misc::MscMax => 0x07,
      Misc::MscCnt => Misc::MscMax.code() + 1,
    }
  }

  /// The literal name of the constant as it appears in the Linux kernel header.
  pub fn name(&self) -> &'static str {
    match self {
      Misc::MscSerial => "MSC_SERIAL",
      Misc::MscPulseled => "MSC_PULSELED",
      Misc::MscGesture => "MSC_GESTURE",
      Misc::MscRaw => "MSC_RAW",
      Misc::MscScan => "MSC_SCAN",
      Misc::MscTimestamp => "MSC_TIMESTAMP",
      Misc::MscMax => "MSC_MAX",
      Misc::MscCnt => "MSC_CNT",
    }
  }
}

/// LEDs
///
/// Do not add any new LED definitions to the input subsystem. The existing
/// definitions are legacy and grandfathered for backwards compatibility with
/// userspace (via evdev). Any new LEDs should be implemented using the
/// LED subsystem (struct led_classdev). The input core provides a bridge to
/// the LED subsystem in drivers/input/input-leds.c.
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum Led {
  LedNuml,
  LedCapsl,
  LedScrolll,
  LedCompose,
  LedKana,
  LedSleep,
  LedSuspend,
  LedMute,
  LedMisc,
  LedMail,
  LedCharging,
  LedMax,
  LedCnt,
}

impl Led {
  /// The raw numeric event code, as defined by the Linux kernel.
  pub fn code(&self) -> u32 {
    match self {
      Led::LedNuml => 0x00,
      Led::LedCapsl => 0x01,
      Led::LedScrolll => 0x02,
      Led::LedCompose => 0x03,
      Led::LedKana => 0x04,
      Led::LedSleep => 0x05,
      Led::LedSuspend => 0x06,
      Led::LedMute => 0x07,
      Led::LedMisc => 0x08,
      Led::LedMail => 0x09,
      Led::LedCharging => 0x0a,
      Led::LedMax => 0x0f,
      Led::LedCnt => Led::LedMax.code() + 1,
    }
  }

  /// The literal name of the constant as it appears in the Linux kernel header.
  pub fn name(&self) -> &'static str {
    match self {
      Led::LedNuml => "LED_NUML",
      Led::LedCapsl => "LED_CAPSL",
      Led::LedScrolll => "LED_SCROLLL",
      Led::LedCompose => "LED_COMPOSE",
      Led::LedKana => "LED_KANA",
      Led::LedSleep => "LED_SLEEP",
      Led::LedSuspend => "LED_SUSPEND",
      Led::LedMute => "LED_MUTE",
      Led::LedMisc => "LED_MISC",
      Led::LedMail => "LED_MAIL",
      Led::LedCharging => "LED_CHARGING",
      Led::LedMax => "LED_MAX",
      Led::LedCnt => "LED_CNT",
    }
  }
}

/// Autorepeat values
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum Autorepeat {
  RepDelay,
  RepPeriod,
  RepMax,
  RepCnt,
}

impl Autorepeat {
  /// The raw numeric event code, as defined by the Linux kernel.
  pub fn code(&self) -> u32 {
    match self {
      Autorepeat::RepDelay => 0x00,
      Autorepeat::RepPeriod => 0x01,
      Autorepeat::RepMax => 0x01,
      Autorepeat::RepCnt => Autorepeat::RepMax.code() + 1,
    }
  }

  /// The literal name of the constant as it appears in the Linux kernel header.
  pub fn name(&self) -> &'static str {
    match self {
      Autorepeat::RepDelay => "REP_DELAY",
      Autorepeat::RepPeriod => "REP_PERIOD",
      Autorepeat::RepMax => "REP_MAX",
      Autorepeat::RepCnt => "REP_CNT",
    }
  }
}

/// Sounds
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum Sound {
  SndClick,
  SndBell,
  SndTone,
  SndMax,
  SndCnt,
}

impl Sound {
  /// The raw numeric event code, as defined by the Linux kernel.
  pub fn code(&self) -> u32 {
    match self {
      Sound::SndClick => 0x00,
      Sound::SndBell => 0x01,
      Sound::SndTone => 0x02,
      Sound::SndMax => 0x07,
      Sound::SndCnt => Sound::SndMax.code() + 1,
    }
  }

  /// The literal name of the constant as it appears in the Linux kernel header.
  pub fn name(&self) -> &'static str {
    match self {
      Sound::SndClick => "SND_CLICK",
      Sound::SndBell => "SND_BELL",
      Sound::SndTone => "SND_TONE",
      Sound::SndMax => "SND_MAX",
      Sound::SndCnt => "SND_CNT",
    }
  }
}

/// ABS_SND_PROFILE values
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum SoundProfile {
  SndProfileSilent,
  SndProfileVibrate,
  SndProfileRing,
}

impl SoundProfile {
  /// The raw numeric event code, as defined by the Linux kernel.
  pub fn code(&self) -> u32 {
    match self {
      SoundProfile::SndProfileSilent => 0x00,
      SoundProfile::SndProfileVibrate => 0x01,
      SoundProfile::SndProfileRing => 0x02,
    }
  }

  /// The literal name of the constant as it appears in the Linux kernel header.
  pub fn name(&self) -> &'static str {
    match self {
      SoundProfile::SndProfileSilent => "SND_PROFILE_SILENT",
      SoundProfile::SndProfileVibrate => "SND_PROFILE_VIBRATE",
      SoundProfile::SndProfileRing => "SND_PROFILE_RING",
    }
  }
}
