//! Structures used in ioctls to upload effects to a device. They are pieces of
//! a bigger structure (called [`FfEffect`]).
//!
//! All duration values are expressed in ms. Values above 32767 ms (0x7fff)
//! should not be used and have unspecified results.

use std::fmt;
use std::mem::zeroed;

/// `struct ff_replay` - defines scheduling of the force-feedback effect
#[repr(C)]
#[derive(Debug, Default, PartialEq, Eq, Clone, Copy)]
pub struct FfReplay {
  /// duration of the effect
  pub length: u16,
  /// delay before effect should start playing
  pub delay: u16,
}

/// `struct ff_trigger` - defines what triggers the force-feedback effect
#[repr(C)]
#[derive(Debug, Default, PartialEq, Eq, Clone, Copy)]
pub struct FfTrigger {
  /// number of the button triggering the effect
  pub button: u16,
  /// controls how soon the effect can be re-triggered
  pub interval: u16,
}

/// `struct ff_envelope` - generic force-feedback effect envelope
///
/// The `attack_level` and `fade_level` are absolute values; when applying
/// envelope force-feedback core will convert to positive/negative
/// value based on polarity of the default level of the effect.
/// Valid range for the attack and fade levels is 0x0000 - 0x7fff
#[repr(C)]
#[derive(Debug, Default, PartialEq, Eq, Clone, Copy)]
pub struct FfEnvelope {
  /// duration of the attack (ms)
  pub attack_length: u16,
  /// level at the beginning of the attack
  pub attack_level: u16,
  /// duration of fade (ms)
  pub fade_length: u16,
  /// level at the end of fade
  pub fade_level: u16,
}

/// `struct ff_constant_effect` - defines parameters of a constant force-feedback effect
#[repr(C)]
#[derive(Debug, Default, PartialEq, Eq, Clone, Copy)]
pub struct FfConstantEffect {
  /// strength of the effect; may be negative
  pub level: i16,
  pub envelope: FfEnvelope,
}

/// `struct ff_ramp_effect` - defines parameters of a ramp force-feedback effect
#[repr(C)]
#[derive(Debug, Default, PartialEq, Eq, Clone, Copy)]
pub struct FfRampEffect {
  /// beginning strength of the effect; may be negative
  pub start_level: i16,
  /// final strength of the effect; may be negative
  pub end_level: i16,
  pub envelope: FfEnvelope,
}

/// `struct ff_condition_effect` - defines a spring or friction force-feedback effect
#[repr(C)]
#[derive(Debug, Default, PartialEq, Eq, Clone, Copy)]
pub struct FfConditionEffect {
  /// maximum level when joystick moved all way to the right
  pub right_saturation: u16,
  /// same for the left side
  pub left_saturation: u16,

  /// controls how fast the force grows when the joystick moves to the right
  pub right_coeff: i16,
  /// same for the left side
  pub left_coeff: i16,

  /// size of the dead zone, where no force is produced
  pub deadband: u16,
  /// position of the dead zone
  pub center: i16,
}

/// `struct ff_periodic_effect` - defines parameters of a periodic force-feedback effect
///
/// Known waveforms - `FF_SQUARE`, `FF_TRIANGLE`, `FF_SINE`, `FF_SAW_UP`,
/// `FF_SAW_DOWN`, `FF_CUSTOM`. The exact syntax `FF_CUSTOM` is undefined
/// for the time being as no driver supports it yet.
///
/// Note: the data pointed by `custom_data` is copied by the driver.
/// You can therefore dispose of the memory after the upload/update.
#[repr(C)]
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub struct FfPeriodicEffect {
  /// kind of the effect (wave), one of [`FfWaveform`](super::FfWaveform)'s codes
  pub waveform: u16,
  /// period of the wave (ms)
  pub period: u16,
  /// peak value
  pub magnitude: i16,
  /// mean value of the wave (roughly)
  pub offset: i16,
  /// 'horizontal' shift
  pub phase: u16,

  pub envelope: FfEnvelope,

  /// number of samples (`FF_CUSTOM` only)
  pub custom_len: u32,
  /// buffer of samples (`FF_CUSTOM` only)
  pub custom_data: *mut i16,
}

impl Default for FfPeriodicEffect {
  fn default() -> Self {
    FfPeriodicEffect {
      waveform: 0,
      period: 0,
      magnitude: 0,
      offset: 0,
      phase: 0,
      envelope: FfEnvelope::default(),
      custom_len: 0,
      custom_data: std::ptr::null_mut(),
    }
  }
}

/// `struct ff_rumble_effect` - defines parameters of a periodic force-feedback effect
///
/// Some rumble pads have two motors of different weight. `strong_magnitude`
/// represents the magnitude of the vibration generated by the heavy one.
#[repr(C)]
#[derive(Debug, Default, PartialEq, Eq, Clone, Copy)]
pub struct FfRumbleEffect {
  /// magnitude of the heavy motor
  pub strong_magnitude: u16,
  /// magnitude of the light one
  pub weak_magnitude: u16,
}

/// `struct ff_haptic_effect`
#[repr(C)]
#[derive(Debug, Default, PartialEq, Eq, Clone, Copy)]
pub struct FfHapticEffect {
  /// hid_usage according to Haptics page (WAVEFORM_CLICK, etc.)
  pub hid_usage: u16,
  /// the waveform vendor ID if hid_usage is in the vendor-defined range
  pub vendor_id: u16,
  /// the vendor waveform page if hid_usage is in the vendor-defined range
  pub vendor_waveform_page: u8,
  /// strength of the effect as percentage
  pub intensity: u16,
  /// number of times to retrigger effect
  pub repeat_count: u16,
  /// time before effect is retriggered (in ms)
  pub retrigger_period: u16,
}

/// The effect-specific anonymous `union u` of `struct ff_effect`.
///
/// Which member is valid is determined by [`FfEffect::type`].
#[repr(C)]
#[derive(Clone, Copy)]
pub union FfEffectData {
  pub constant: FfConstantEffect,
  pub ramp: FfRampEffect,
  pub periodic: FfPeriodicEffect,
  /// One for each axis
  pub condition: [FfConditionEffect; 2],
  pub rumble: FfRumbleEffect,
  pub haptic: FfHapticEffect,
}

impl Default for FfEffectData {
  fn default() -> Self {
    // All-zero is a valid bit pattern for every member (including the null
    // `custom_data` pointer).
    unsafe { zeroed() }
  }
}

impl fmt::Debug for FfEffectData {
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    f.debug_struct("FfEffectData").finish_non_exhaustive()
  }
}

/// `struct ff_effect` - defines force feedback effect
///
/// This structure is sent through ioctl from the application to the driver.
/// To create a new effect application should set its `id` to -1; the kernel
/// will return assigned `id` which can later be used to update or delete
/// this effect.
///
/// Direction of the effect is encoded as follows:
/// - 0 deg -> 0x0000 (down)
/// - 90 deg -> 0x4000 (left)
/// - 180 deg -> 0x8000 (up)
/// - 270 deg -> 0xC000 (right)
#[repr(C)]
#[derive(Debug, Default, Clone, Copy)]
pub struct FfEffect {
  /// type of the effect, one of [`FfEffectType`](super::FfEffectType)'s codes
  /// (`FF_CONSTANT`, `FF_PERIODIC`, `FF_RAMP`, `FF_SPRING`, `FF_FRICTION`,
  /// `FF_DAMPER`, `FF_RUMBLE`, `FF_INERTIA`, or `FF_CUSTOM`)
  pub r#type: u16,
  /// an unique id assigned to an effect
  pub id: i16,
  /// direction of the effect
  pub direction: u16,
  /// trigger conditions
  pub trigger: FfTrigger,
  /// scheduling of the effect
  pub replay: FfReplay,
  /// effect-specific structure further defining effect parameters
  pub u: FfEffectData,
}
